### ISSUE TITLE
Mehrfache Icons im Backend

### ISSUE THREAD

**Issue by Baecker** [firegento/firegento-germansetup#100]
Nach Installation des German Setup sind nun die Icons auf verschiedenen Buttons dreifach vorhanden. Wie kommt das?

**Comment by avstudnitz** [comment]
Welche Buttons? Welche Icons? Bitte um Details und Screenshots - ich habe das hier nicht (oder noch nicht gefunden).

**Comment by Baecker** [comment]
Es betraf alle Buttons, wo Icons drauf sind "Löschen, Neu anlegen" usw... Seltsamerweise sind sie nun wieder weg (nur einmal vorhanden)...

**Comment by riconeitzel** [comment]
demnach ein zufälliges, temporäres Phänomen … ich schließe das mal. Falls das reproduzierbar wieder auftritt einfach den Fall hier wieder öffnen! Danke :-)
