### ISSUE TITLE
Fehler Update von 1.1.2 auf 1.1.4 über Connect Manager

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-germansetup#101]
Bei einem Update über den Connect Manager wird nicht der komplette Code installiert. Ich hatte anschliessend folgende Fehler im system.log.

> 2012-12-04T10:30:22+00:00 ERR (3): Warning: include(FireGento/GermanSetup/Helper/Checkout/Data.php): failed to open stream: No such file or directory  in /var/www/web/magento/lib/Varien/Autoload.php on line 93
> 2012-12-04T10:30:22+00:00 ERR (3): Warning: include(): Failed opening 'FireGento/GermanSetup/Helper/Checkout/Data.php' for inclusion (include_path='/var/www/web/magento/app/code/local:/var/www/web/magento/app/code/community:/var/www/web/magento/app/code/core:/var/www/web/magento/lib:.:/usr/share/php:/usr/share/pear')  in /var/www/web/magento/lib/Varien/Autoload.php on line 93

Auch ein Reinstall im Connect Manager hat nichts gebracht. Erst ein

```
./mage install community FireGento_GermanSetup --force
```

hat dann das komplette Packet installiert. ich weiß nicht ob das ein Fehler des Connect Managers oder GermanSetup ist. Auf jeden Fall führt es zu einem funktionsunfähigen Shop, wenn man den Connectmanager nutzt.

**Comment by mklooss** [comment]
ist der Compiler an, und ist die Datei auch vorhanden?

> FireGento/GermanSetup/Helper/Checkout/Data.php

**Comment by grossmann** [comment]
Compiler weiß ich nicht. Wo stellt man den an?
Die Dateien sind nach einem Upgrade mit Magento Connect **nicht** vorhanden (darum ja der Fehler, ich hatte das nicht so explizit geschrieben), es wird im Connect Manager aber die neue Version angezeigt. Erst über die Komandozeile mit der option `--force` wurden alle Dateien der neuen Version auch tatsächlich installiert.

Edit: ich vermute, dass das ein Fehler vom (schrottigen) Connect Manager ist. Ich hatte da auch schon mit anderen Modul-Updates Probleme

**Comment by grossmann** [comment]
Hä, wiso ist das jetzt closed? Ich war's nicht, ehrlich.

**Comment by riconeitzel** [comment]
Das wurde bestimmt von Dir geschlossen, weil es ein Problem des Magento Connect Managers ist und kein Problem mit dieser Extension :-) Daher kannst Du auch wieder auf Close klicken, wenn Du möchtest :-)

Liebe Grüße
 Rico

**Comment by grossmann** [comment]
Ja, ich geb's zu, ich war's (mit dem close, nicht mit dem buggy Connect Manager).

Gruß

p.s. Mist, jetzt ist das Issue schon zu ;-)
