### ISSUE TITLE
Support request: Price info block ausblenden für nicht angemeldete Kunden

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-germansetup#102]
Ich möchte die zusätzlichen Preisinfos (aus price_info.phtml) für nicht angemeldete Kunden ausblenden. Dazu versuche ich in der local.xml mit folgendem Code den Block zu entfernen.

```
<customer_logged_out>
  <reference name="content">
    <action method="unsetChild"><name>price_info</name></action>
  </reference>
</customer_logged_out>
```

Jedoch scheint der Block keinen Namen zu haben, da er programatisch Price.php erzeugt wird. Gibt es noch einen anderen Weg, diesen Block für anonyme Kunden auszublenden?

**Comment by mklooss** [comment]
In der Template Datei, kannst du auch Abfragen einbauen

**Comment by riconeitzel** [comment]
Habe unter #113 mehr css klassen definiert. per local XML lässt sich dann einfach eine CSS-Datei einbinden, die dinger versteckt, wenn der Kunde nicht angemeldet ist. das ist dann zwar nicht aus'm code raus, aber immerhin nicht sichtbar.

**Comment by grossmann** [comment]
Danke!
