### ISSUE TITLE
Geschäftsführer/Inhaber für TMG §5 Ausgabe

### ISSUE THREAD

**Issue by riconeitzel** [firegento/firegento-germansetup#105]
Je nach Geschäftsart hat eine Firma vllt. keinen CEO, dieses Feld wird aber beim TMG §5 ausgegeben. Ich schlage vor, dass man für den inhaltlich Verantwortlichen ein eigenes Eingabefeld im Backend anlegt.

PullRequest kommt vllt noch.

LG Rico

**Comment by avstudnitz** [comment]
Ja, klingt sinnvoll. Wir haben Felder für Geschätsführer und Inhaber, von denen ja üblicherweise nur eins befüllt sein sollte. Ein zusätzliches Feld für den Inhaltlich Verantwortlichen wäre gut.

**Comment by riconeitzel** [comment]
pullrequest ist schon in vorbereitung :)

bin aber noch an der steuerklassen-sache dran :)

**Comment by riconeitzel** [comment]
Ist mit #110 erledigt
