### ISSUE TITLE
Plugin nicht installiert?

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-germansetup#106]
Hallo, ich habe FireGento in meinem frisch installierten Magento-Shop mittels dem Magento Connect Manager installiert. Und was jetzt?
Ich sehe weder eine Meldung noch finde ich die Einstellungen und mein ganzes System ist auch noch auf englisch. Mache ich etwas falsch?

**Comment by drlrdsen** [comment]
Hallo Robert,

GermanSetup ist keine Übersetzung des Magento-Systems und im Sinne der allgemeinen Einsetzbarkeit haben wir das Modul bewusst von anderen Modulen unabhängig gehalten. Du solltest im Backend unter System -> German Setup einige neue Einstellungsmöglichkeiten finden, um beispielweise Steuerregelungen einzustellen. Wenn du das deutsche Sprachpaket installieren möchtest, kann ich dir http://www.magentocommerce.com/magento-connect/locale-mage-community-de-de.html empfehlen.

Viele Grüße
Michael

**Comment by ghost** [comment]
Danke für die Antwort. Das Problem war die Berechtigung. Ich hatte alle erforderlichen Rechte auf 777 gesetzt. Anscheinend hat aber etwas gefehlt und die Installation war "successful", aber eben nicht aufrufbar.
