### ISSUE TITLE
Version 1.1.4 funktioniert nicht unter Mage+ v1.0.0.8

### ISSUE THREAD

**Issue by JumpLink** [firegento/firegento-germansetup#107]
Version 1.1.4 funktioniert nicht unter [Mage+](http://www.mageplus.org/) v1.0.0.8.
- Der Kompatiblilitätsmodus zu Magento ist aktiviert
- Der Cache ist deaktiviert und die alten Dateien gelöscht
- Der Compiler ist deaktiviert
- Die installation verläuft problemlos
- Der neue Menüeintrag in der Administration ist vorhanden
- Die Log-Dateien sind aktiviert aber leer

Das Problem: Wenn ich auf den neuen Menüeintrag "Setup" klicke bekomme ich nur eine weiße Seite angezeigt, der Header und der Footer werden weiterhin ganz normal angezeigt, nur eben dass ich keine Einstellungsmöglichkeiten für die Erweiterung machen kann, da nichts dafür angezeigt wird.

Irgend eine Idee wie ich nach dem Fehler suchen könnte, ich bekomme ja leider keine Fehlermeldungen angezeigt oder geloggt? Andere Ratschläge/Hilfen?
Ich könnte dann auch ggf. einen Patch bereit stellen.

Danke im Voraus!

Mage+ Issue dazu: https://github.com/mageplus/mageplus/issues/137

**Comment by mklooss** [comment]
hast du schon einmal in die ErrorLog geschaut? also die vom Server?

**Comment by JumpLink** [comment]
Ah nun funktioniert es, lag wohl an irgend welchen falschen Dateirechten die gesetzt waren.
