### ISSUE TITLE
Disable price postfix

### ISSUE THREAD

**Issue by tim-bezhashvyly** [firegento/firegento-germansetup#108]
There's no way to disable price postfix (e.g. incl tax).

**Comment by riconeitzel** [comment]
should there be a way?

**Comment by tim-bezhashvyly** [comment]
If according to german law merchant is not obliged to display the incl/excl tax message everywhere he has price then yes.

**Comment by avstudnitz** [comment]
Should not be a common requirement. Can be removed with CSS as the block has its own class.
On the other hand, it wouldn't harm, so if you create a pull request, I'd be in favor of merging it :-)

**Comment by riconeitzel** [comment]
i'm preparing a more css'ed version.

**Comment by tim-bezhashvyly** [comment]
I prefer giving ppl a choice. Will do a pull request once I have a free moment.

**Comment by riconeitzel** [comment]
hey tim - i'm still working on it, so probably you're willing to extend my solution.

**Comment by riconeitzel** [comment]
Enhanced in #113
