### ISSUE TITLE
UStID nicht auf Impressumsseite ersichtlich n/t

### ISSUE THREAD

**Issue by riconeitzel** [firegento/firegento-germansetup#109]

**Comment by avstudnitz** [comment]
USt.-ID wird jetzt dargestellt. Wenn keine eingegeben ist, wird stattdessen die Steuernummer dargestellt.

**Comment by riconeitzel** [comment]
> USt.-ID wird jetzt dargestellt. Wenn keine eingegeben ist, wird stattdessen die Steuernummer dargestellt.

Darf nicht/muss nicht. Es MUSS die UStID angegeben werden, wenn eine zugeteilt wurde, aber die ESt.Nr. muss nicht angezeigt werden.

**Comment by avstudnitz** [comment]
Okay, dann ist das nur bei Rechnungen so - da muss eins von beidem stehen. Werde es ändern.

**Comment by riconeitzel** [comment]
> Okay, dann ist das nur bei Rechnungen so - da muss eins von beidem stehen. Werde es ändern.

ja, genau so :)
