### ISSUE TITLE
Deinstallation MRG

### ISSUE THREAD

**Issue by Baecker** [firegento/firegento-germansetup#114]
Gibt es eine ausführliche Anleitung, um ein vorhandenes MRG zu deinstallieren? Notfalls auch "von Hand"?
Weiterhin... wo findet man eine Beschreibung zu den verwendbaren Variablen in German Setup?

**Comment by riconeitzel** [comment]
Ich weiß nicht, ob die Deinstallationsfrage hier etwas offtopic ist?!

Wo genau möchtest Du denn die Variablen von GermanSetup verwenden?

**Comment by avstudnitz** [comment]
Ich verweise für die Deinstallation auf das sich in Entwicklung befindende Modul unter https://github.com/firegento/DeinstallMRG. Die Deinstallation des Kernmoduls sollte damit funktionieren.

**Comment by Baecker** [comment]
Ich meine die Variablen, die z.Bsp. in AGB, Transaktionsmails etc. vorkommen (Firmenname, Shopname, Geschäftsführer usw.). Gibt es irgendwo eine Liste mit Beschreibung
