### ISSUE TITLE
CMS-Seiten und Statische Blöcke deaktivieren

### ISSUE THREAD

**Issue by El-Patroni** [firegento/firegento-germansetup#115]
Hi.

Ich habe nach einer frischen Magento-Installation mit dem Standart-Template die Erweiterung German Setup installiert und bei der ersten Konfiguration das Setup: CMS-Seiten und Statische Blöcke erstellen aktiviert gelassen und habe anschließend German Setup ausgeführt. Nun hat German Setup im Footer die Menüs :  
    AGB
    Widerruf
    Lieferung
    Zahlungsarten
    Datenschutz
    Bestellvorgang
    Impressum 

angelegt, was zunächst auch richtig ist. Nach der Instalation eines neuen Magento-Theme befinden sich oben genannten Menüs an einer ungünstigen Stelle im neuen Template. 
Wie kann man diese Menüs/Seiten/Block deaktivieren? Ich würde diese anschließend in dem richtigen Bereich des neuen Theme neu anlegen.

Eine Deaktivierung der Option: "CMS-Seiten und Statische Blöcke erstellen" unter System > German Setup  > Setup und ein anschließendes Ausführen von German Setup hat nichts gebracht. Die Menüs und die Seiten sind immer noch vorhanden.

Über eine Antwort wäre ich Ihnen sehr dankbar.

Vielen Dank.

Mit Freundliche Grüßen

![Support German Setup](https://f.cloud.github.com/assets/3033336/10436/17a91484-4519-11e2-92de-f18420af4be0.PNG)

**Comment by avstudnitz** [comment]
Die Seiten können im Admin-Bereich unter CMS -> Seiten bearbeitet und auch gelöscht werden. Das Menü kommt aus dem statischen Block "footer_links", den du unter CMS -> Statische Blöcke" bearbeiten kannst.

Das Problem scheint hier aber eher das Template zu sein - der richtige Block ist an der falschen Stelle und müsste an die richtige Stelle verschoben werden. Als Lektüre zur Fortbildung in dem Bereich empfehle ich http://store.pulsestorm.net/products/no-frills-magento-layout.
