### ISSUE TITLE
Angaben verschwinden bei Sortierungswechsel

### ISSUE THREAD

**Issue by dEbiL1307** [firegento/firegento-germansetup#116]
Hi
ich weiß nicht ob das ein Problem von dem Plugin ist oder mit meinem Theme zusammenhängt, aber die Zusatzangaben bei den Preisen in der Artikelliste verschwinden bei meinem Shop wenn ich die Sortierung oder die Anzahl der Pro Seite angezeigten Artikel ändere.

Ich kenne mich mit Magento nicht genug aus um im Quellcode rum zu suchen, im HTML Quellcode der Seite ist die span nach einem Wechsel der Ansicht einfach weg.

Vielleicht hat jemand eine Idee und kann mir helfen.

**Comment by avstudnitz** [comment]
Eben getestet - tritt hier nicht auf. Ich vermute ein Problem in deinem Theme.
