### ISSUE TITLE
Bestellbedingungen werden nicht angezeigt im Checkout

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-germansetup#117]
Hallo,

also vorab es handelt sich um ein dazugekauftes Template.
Welche Stellen sind im Template/Modul dafür verantwortlich die Bestellbedingungen anzuzeigen?
Sollte es ein Markup geben? Bevor ich mich daran müde suche, vll. weiß das jemand aus dem Stegreif.
Im Backend ist das ganze auf jeden Fall aktiviert.

Bin dankbar für jede Hilfe, und abseits dessen frohe Festtage!

![checkout](https://f.cloud.github.com/assets/965733/26843/7665a31e-4b5b-11e2-9e36-9f8b6606e111.jpg)

**Comment by mklooss** [comment]
ist das Template ggf. auch für Magento 1.4, dann wird es daran liegen, du musst den Teil "checkout_onepage" in der XML daher vermutlich komplett ersetzen.

Haste es denn schon im Default Theme probiert?

**Comment by easyMaxi** [comment]
Default klappt wunderbar. Das Template ist ursprünglich für 1.4 gewesen aber sollte eigentlich geupdatet werden.... Ich werde mal schauen ob es das ist. Danke für den Tipp!

EDIT: Hab das mal ausprobiert. Lag tatsächlich dran. Super Tipp! Danke
