### ISSUE TITLE
Anzeige zzgl. Versandskosten

### ISSUE THREAD

**Issue by sven99** [firegento/firegento-germansetup#12]
Hallo,

erstmal herzlichen dank für die  tolle Umsetzung!

Bei mir wird seit dem letzten Update (Anzeige Versandskosten bei Downloadprodukten) kein Zusatz der Versandkosten, bei normalen Artikeln mehr angezeigt. Egal welche Produktart ich erstelle.  

Gruß

**Comment by avstudnitz** [comment]
Ich vermute, dir fehlt die Einstellung der Versandkosten-Seite unter System -> Konfiguration -> Katalog -> Preis -> CMS-Seite für Versandkosten. Bei mir funktioniert es nach der Einstellung.

**Comment by sven99** [comment]
Danke! Manchmal sieht man den Wald vor lauter Bäumen nicht!
