### ISSUE TITLE
VAT Thresholds

### ISSUE THREAD

**Issue by florinel-chis** [firegento/firegento-germansetup#120]
When a business passes a certain threshold in sales in a EU country according to the law needs to charge the local VAT (and register for a local VAT number).

If my company is based in Germany and I sell in UK for more than £77,000 or in France more than €100,000 you need to charge local VAT (the amount varies by country).

So in that case, even if I am a company based in Germany on the invoice I need to charge French VAT (19.6, 5.5 - books/audiobooks or 7 as reduced, 0).

Would be nice to be able to configure the module to take into consideration these situations.

**Comment by riconeitzel** [comment]
thanks for that information. could you please give me some links or paragraphs to read more about that? thanks rico

**Comment by florinel-chis** [comment]
VAT Rates:
http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf

Distance selling of goods
http://ec.europa.eu/taxation_customs/taxation/vat/how_vat_works/distance_selling/index_en.htm

Thresholds:
http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/traders/vat_community/vat_in_ec_annexi.pdf

Please let me know if any addition information is needed. I also implemented this for couple of retailers that sell goods worldwide in Austria and UK, in order to be compliant with the law.

**Comment by avstudnitz** [comment]
in my opionion, this goes beyond the goals of the module - it is a good starting point and doesn't have to cover all cases. As it isn't too difficult to configure this by hand (or hire a professional for that - if you exceed the threshold, you will be able to pay him), we shouldn't complicate the setup process with this.

**Comment by riconeitzel** [comment]
ACK
