### ISSUE TITLE
Mage_Core_Exception: Invalid block type

### ISSUE THREAD

**Issue by fao3euPh** [firegento/firegento-germansetup#121]
Hi,

wie es scheint, haben wir haben ein Paar Probleme mit der Extension auf Magento 1.7.0.2.

Die untenstehende Meldung wird in die Log-Files geschrieben, wenn Kunden die Zahlungs-Details angeben.

exception \\’Mage_Core_Exception\\’ with message \\’UngÃ¼ltiger Blocktyp: Mage_Imprint_Block_Content\\’ in /htdocs/app/Mage.php:594
Stack trace:
#0 /htdocs/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException(\\’Ung??ltiger Blo...\\’)
#1 /htdocs/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance(\\’imprint/content\\’, Array)
#2 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(164): Mage_Core_Model_Layout->createBlock(\\’imprint/content\\’, NULL, Array)
#3 [internal function]: Mage_Core_Model_Email_Template_Filter->blockDirective(Array)
#4 /htdocs/lib/Varien/Filter/Template.php(134): call_user_func(Array, Array)
#5 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(502): Varien_Filter_Template->filter(\\’<h3>1. Geltungs...\\’)
#6 /htdocs/app/code/core/Mage/Cms/Block/Block.php(54): Mage_Core_Model_Email_Template_Filter->filter(\\’<h3>1. Geltungs...\\’)
#7 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Cms_Block_Block->_toHtml()
#8 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(191): Mage_Core_Block_Abstract->toHtml()
#9 [internal function]: Mage_Core_Model_Email_Template_Filter->blockDirective(Array)
#10 /htdocs/lib/Varien/Filter/Template.php(134): call_user_func(Array, Array)
#11 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(502): Varien_Filter_Template->filter(\\’{{block type=\\"c...\\’)
#12 /htdocs/app/code/community/FireGento/GermanSetup/Model/Observer.php(101): Mage_Core_Model_Email_Template_Filter->filter(\\’{{block type=\\"c...\\’)
#13 /htdocs/app/code/community/FireGento/GermanSetup/Model/Observer.php(81): FireGento_GermanSetup_Model_Observer->_filterString(\\’{{block type=\\"c...\\’)
#14 /htdocs/app/code/core/Mage/Core/Model/App.php(1338): FireGento_GermanSetup_Model_Observer->filterAgreements(Object(Varien_Event_Observer))
#15 /htdocs/app/code/core/Mage/Core/Model/App.php(1311): Mage_Core_Model_App->_callObserverMethod(Object(FireGento_GermanSetup_Model_Observer), \\’filterAgreement...\\’, Object(Varien_Event_Observer))
#16 /htdocs/app/Mage.php(447): Mage_Core_Model_App->dispatchEvent(\\’core_block_abst...\\’, Array)
#17 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(850): Mage::dispatchEvent(\\’core_block_abst...\\’, Array)
#18 /htdocs/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#19 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Text_List->_toHtml()
#20 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(582): Mage_Core_Block_Abstract->toHtml()
#21 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(526): Mage_Core_Block_Abstract->_getChildHtml(\\’items_before\\’, true)
#22 /htdocs/app/design/frontend/base/default/template/checkout/onepage/review/info.phtml(27): Mage_Core_Block_Abstract->getChildHtml(\\’items_before\\’)
#23 /htdocs/app/code/core/Mage/Core/Block/Template.php(241): include(\\’/var/www/virtua...\\’)
#24 /htdocs/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView(\\’frontend/base/d...\\’)
#25 /htdocs/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#26 /htdocs/app/code/core/Mage/Core/Block/Abstract.php(863): Mage_Core_Block_Template->_toHtml()
#27 /htdocs/app/code/core/Mage/Checkout/controllers/OnepageController.php(145): Mage_Core_Block_Abstract->toHtml()
#28 /htdocs/app/code/core/Mage/Checkout/controllers/OnepageController.php(432): Mage_Checkout_OnepageController->_getReviewHtml()
#29 /htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Checkout_OnepageController->savePaymentAction()
#30 /htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch(\\’savePayment\\’)
#31 /htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#32 /htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#33 /htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#34 /htdocs/index.php(87): Mage::run(\\’babygarage\\’, \\’website\\’)

When the order is submitted, it looks like that:

2012-10-27T19:13:27+00:00 ERR (3):
exception \\’Mage_Core_Exception\\’ with message \\’UngÃ¼ltiger Blocktyp: Mage_Imprint_Block_Content\\’ in /htdocs/app/Mage.php:594
Stack trace:
#0 /htdocs/app/code/core/Mage/Core/Model/Layout.php(495): Mage::throwException(\\’Ung??ltiger Blo...\\’)
#1 /htdocs/app/code/core/Mage/Core/Model/Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance(\\’imprint/content\\’, Array)
#2 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(164): Mage_Core_Model_Layout->createBlock(\\’imprint/content\\’, NULL, Array)
#3 [internal function]: Mage_Core_Model_Email_Template_Filter->blockDirective(Array)
#4 /htdocs/lib/Varien/Filter/Template.php(134): call_user_func(Array, Array)
#5 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Filter.php(502): Varien_Filter_Template->filter(\\’<style type=\\"te...\\’)
#6 /htdocs/app/code/core/Mage/Core/Model/Email/Template.php(345): Mage_Core_Model_Email_Template_Filter->filter(\\’<style type=\\"te...\\’)
#7 /htdocs/app/code/core/Mage/Core/Model/Email/Template.php(442): Mage_Core_Model_Email_Template->getProcessedTemplate(Array, true)
#8 /htdocs/app/code/core/Mage/Core/Model/Email/Template.php(506): Mage_Core_Model_Email_Template->send(Array, Array, Array)
#9 /htdocs/app/code/core/Mage/Core/Model/Email/Template/Mailer.php(79): Mage_Core_Model_Email_Template->sendTransactional(\\’65\\’, \\’general\\’, Array, Array, Array, \\’9\\’)
#10 /htdocs/app/code/core/Mage/Sales/Model/Order.php(1321): Mage_Core_Model_Email_Template_Mailer->send()
#11 /htdocs/app/code/core/Mage/Checkout/Model/Type/Onepage.php(803): Mage_Sales_Model_Order->sendNewOrderEmail()
#12 /htdocs/app/code/core/Mage/Checkout/controllers/OnepageController.php(511): Mage_Checkout_Model_Type_Onepage->saveOrder()
#13 /htdocs/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Mage_Checkout_OnepageController->saveOrderAction()
#14 /htdocs/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch(\\’saveOrder\\’)
#15 /htdocs/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 /htdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 /htdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#18 /htdocs/index.php(87): Mage::run(\\’babygarage\\’, \\’website\\’)

Habt Ihr einen Rat, wie wir das beheben können?

Danke & Gruss.

**Comment by riconeitzel** [comment]
Sicher, dass das im Zusammenspiel mit GermanSetup entsteht?

**Comment by riconeitzel** [comment]
Hattet ihr vorher Symmetrics_MarketReadyGermany laufen?

**Comment by fao3euPh** [comment]
yep, Symmetrics_MarketReadyGermany war vorher drauf. 

ich habe alles mögliche gelöscht.

hast du einen verdacht?

**Comment by riconeitzel** [comment]
Da liegt das Problem. Symmetrics_Imprint hieß das alte Modul … keine Ahnung von dem Ding, bisher. Leider.
