### ISSUE TITLE
Install on international shop

### ISSUE THREAD

**Issue by paales** [firegento/firegento-germansetup#122]
We are currently running a Dutch and UK storefront. We would like to install your module, but all the settings, pages etc need to be installed on the German website.

I've previously tried the german modules but they all were a module for a new shop and nothing that could be used on an existing installation (it all overwrites the admin config values).

**Comment by riconeitzel** [comment]
In this case I think it's easier to setup these values by hand rather than modifing that script. That modules intention is to initially setup your magento instance, not implement german config values on a single store view.

best,
 rico

**Comment by paales** [comment]
Thanks for the response. Besides the automatic settings there of course are a few functionalities that come in handy for any shop operating in german.

Are the settings automatically set up on install or are they installed by pressing a button?

**Comment by riconeitzel** [comment]
You have to press a button to use auto configuration :)

Best,
 Rico

**Comment by avstudnitz** [comment]
Yes, nothing is overwritten automatically, you can install the module without any danger. There is the additional option to run the setup process from another module with php, see issue #95 (only in development branch right now).
