### ISSUE TITLE
AGBs bei Registrierung abfragen

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#123]
Wäre es in-scope von germansetup eine Option zu bieten Bestellbedigungen auch direkt bei Benutzernanmeldung anzuzeigen und bestätigen zu lassen?

Ist soetwas nach dem deutschen Rechtssystem (in machen Fällen) überhaupt nötig? Oder eher unnötig?

Hier wäre ggf. eine neue Einstellung nötig, so das man auswählen kann, welche Bedingungen überhaupt bei der Anmeldung angezeigt werden sollen.

**Comment by riconeitzel** [comment]
Also nach dt. Recht ist das nicht verpflichtend. Das müsste ggf. im einzelnen Geschäftsmodell definiert werden. Ob das im Rahmen von F-GS umgesetzt werden könnte, kann ich nicht entscheiden. Ggf. wäre das ne eigene Extension wert, die F-GS als Abhängigkeit voraussetzt?

rico

**Comment by mklooss** [comment]
In manchen fällen müsste der Datenschutz mit rein. aber nicht immer (wie rico schon schrieb), wenn würde es hier sinn machen, eine "Kopie" der bedigungen zu machen und Extra Register-bedigungenerstellen.

**Comment by amenk** [comment]
Dann müsste man aber beispielsweise die AGB doppelt pflegen. Fände ich zu aufwändig. Warum nicht ein Flag "Anzeigen bei Registrierung". 
Natürlich ist der Menüpunkt unter "Verkäufe" dann irgendwie falsch :-( ungünstig.

**Comment by mklooss** [comment]
naja, im "Normalfall" stehen dort ja nicht die AGB direkt, sondern die Verknüpfung zum Statischen Block.

**Comment by riconeitzel** [comment]
Ja, die Pflege der Texte ist in jedem Fall im Static Block zu erledigen. Wäre nun die Frage nach der Konzeption:

1.) Bestellbedingungen um eine Checkbox "[ ] Bei Benutzerregistrierung anzeigen" erweitern, oder

2.) In der System->Konfiguration unter Kundenkonfiguration -> Anmeldeoptionen ein Dropdown Aktiviert/Deaktivert "Bestellbedingungen des Bestellvorgangs auch bei der Benutzerregistrierung anzeigen"

3.) Die Frage: Sollte das in F-GS rein oder nicht?

Ich schätze, dass 2.) schneller realisiert ist und per Observer eingeklinkt werden kann.

Warten wir mal Feedback der anderen Teammitglieder ab.

**Comment by riconeitzel** [comment]
War nicht mal ein Observer nötig. Mal sehen …

**Comment by amenk** [comment]
Danke, Rico.
Jetzt gibt es aber nur alle Bestellbedingungen und nicht die Option z.B. nur die AGB bei Registrierung abzufragen, bei Bestellung hingegeben aber auch die Widerrufsbelehrung.

Verstehe ich das richtig, dass die Validierung nur in Javascript erfolgt und nicht serverseitig?

**Comment by amenk** [comment]
Diskussion wird in #124 fortgesetzt.
