### ISSUE TITLE
Doppelte Ausgabe von inkl.MwSt. zzgl.Versandkosten bei Installation von BCP

### ISSUE THREAD

**Issue by sepp2006** [firegento/firegento-germansetup#125]
Bei installation von BCP (better configurable products)
wird bei artikeln mit dropdown auswahl der Text
Inkl. MwSt. zzgl. Versandkosten Doppelt angezeigt.
Gibt es eine Lösung dafür?
![german-setup-bcp](https://f.cloud.github.com/assets/3246120/109967/62194ff4-6aa6-11e2-9d38-f12bd3e71bc9.jpg)

**Comment by ttuchtfeldt** [comment]
Oben genannten Fehler kann ich auch bestätigen bei Nutzung der Erweiterung von BCP (better configurable products
Der doppelte Eintrag wird  wohl über den Eintrag 
<?php echo $this->getTierPriceHtml() ?>
in der catalogproductview.phtml erzeugt.

**Comment by cojaco** [comment]
Als Workaround hab ich das per jquery und css gelöst.
per php wäre natürlich eleganter.

$('.product-shop-right').each(function() {
    $('.tax-details.relevant').slice(0).addClass('no1');
    $('.tax-details.relevant').slice(1).addClass('no2');
    $(".tax-details.relevant.no2").prependTo("ul.tier-prices.product-pricing li"); //der zweite td text wird in den unsichtbaren ul li container da drüber verschoben.
    });

um ein springen zu verhindern: am besten noch folgendes css einfügen
.product-shop .tax-details { display: none;}
.product-shop .tax-details.no1,
.product-shop .tax-details.no2 {display: block; ....
