### ISSUE TITLE
Gruppenprodukte in Kategorieansicht mit 0% MwSt

### ISSUE THREAD

**Issue by thisisklara** [firegento/firegento-germansetup#127]
Hallo zusammen,

bei meinem Magento 1.7.0.2 wird in der Kategorieansicht bei allen Gruppenprodukten "zzgl. 0% Mwst" angezeigt, obwohl die Einzelprodukte in den Gruppen zzgl 19% Mwst.

Gruppenprodukten kann man ja bekanntlich keine Steuersätze zuweisen.

Hab ich was falsch eingestellt, oder könnte das ein Bug sein? 
Für schnelle Hilfe wäre ich super dankbar - der Shop soll demnächst online gehen!

Viele Grüße
klara

**Comment by thisisklara** [comment]
Hat keiner eine Lösung?

**Comment by thisisklara** [comment]
Ok, hab's jetzt mit einem Workaround gelöst und das Attribut tax classes auch für die Gruppenprodukte aktiviert. 
Schön wäre aber, wenn sich das beim nächsten Update vielleicht so machen ließe, dass sich die Steuerklasse bei den Gruppenprodukten aus den steuerklassen der Einzelprodukte ergibt - dann klappt's auch für Gruppen mit Produkten unterschiedlicher Steuersätze.

*Monolog Ende

**Comment by mklooss** [comment]
und wie sieht deine Lösung aus?
