### ISSUE TITLE
Übersetzungen greifen nicht

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#128]
Kommentar in meinem Blog - Email-Adresse ist mir bekannt:

Hallo brauche euren Rat!
Bei mir wird bei den Produkten immer angezeigt:

Incl. 19% Tax, excl. Shipping Cost

Ich habe German Setup installiert und alles angelegt.
Dann habe ich auch versucht in mein Template /locale/de_DE/translate.csv es einzustellen:

```
“Incl. Tax, plus <a href=""%s"">Shipping Cost</a>","Inkl. MwSt., zzgl. <a dummy=""%s"” href=""%s"">Versand</a>"
“Incl. %s Tax, plus <a href=""%s"">Shipping Cost</a>","Inkl.%s MwSt., zzgl. <a dummy=""%s"” href=""%s"">Versand</a>"
“Excl. %s Tax, plus <a href=""%s"">Shipping Cost</a>","Zzgl. %s MwSt., zzgl. <a dummy=""%s"” href=""%s"">Versand</a>"
“Incl. Tax","Inkl. MwSt.”
“Incl. %s Tax","Inkl. MwSt.”
“Excl. %s Tax","Zzgl. MwSt.”
```

Leider ohne Erfolg, den Cashe habe ich auch komplett geleert!
Jetzt weis ich nicht weiter. Bitte um Hilfe…

Benurtze Magento 1.7.0.2 was über Plesk installiert wurde und nutze es als MultiStore.

Danke

**Comment by avstudnitz** [comment]
Vermutung: die Anführungszeichen sehen teilweise so aus, als wären es die falschen, z.B. die letzten bei <a dummy=""%s"”. Kann es daran liegen?

**Comment by Clickpool** [comment]
Ich habe es mal geändert in:

```
"Incl. Tax, plus <a href=""%s"">Shipping Cost</a>","Inkl. MwSt., zzgl. <a dummy=""%s"" href=""%s"">Versandkosten</a>"
"Incl. %s Tax, plus <a href=""%s"">Shipping Cost</a>","Inkl. %s MwSt., zzgl. <a dummy=""%s"" href=""%s"">Versandkosten</a>"
"Excl. %s Tax, plus <a href=""%s"">Shipping Cost</a>","Zzgl. %s MwSt., zzgl. <a dummy=""%s"" href=""%s"">Versandkosten</a>"
"Incl. Tax","Inkl. MwSt."
"Incl. %s Tax","Inkl. %s MwSt."
"Excl. %s Tax","Zzgl. %s MwSt."
```

Und die Datei mit Notepad++ in Kodierung UTF-8 ohne BOM gespeichert und getestet, aber wieder nix.

**Comment by mklooss** [comment]
das kann manchmal passieren schreibmal den Scope dazu

```
"FireGento_GermanSetup::Original","Neuer Text"
```

**Comment by riconeitzel** [comment]
Außerdem: DeveloperMode On macht auch, dass nicht alle Übersetzungen greifen!

**Comment by therouv** [comment]
In der aktuellen Version ist das Problem nicht vorhanden, oder? Zumindest kann ich es nicht reproduzieren.
