### ISSUE TITLE
Trusted Shops: Button-Lösung

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#134]
> 1. Frage: Lässt sich die Artikelbeschreibung (optimal wäre per Option entweder
>    Kurzbeschreibung, lange Beschreibung oder ein freier Text) auf der Bestellseite, bzw. dem
>    Tab "5. Bestellübersicht" beim Artikelnamen anzeigen?

Hatten wir sowas nicht? Oder war das in dem Modul von @mklooss enthalten? Dann sollten wir das evtl. in GermanSetup integrieren.

**Comment by riconeitzel** [comment]
ich glaube das ist buggy. hab ich heute in der schulung gemerkt. LG Rico

**Comment by avstudnitz** [comment]
Funktioniert bei mir, ich habe es gefunden. In den Attributeigenschaften kann man "Sichtbar im Bestellprozess" (is_visible_on_checkout) aktivieren. @riconeitzel: Prüfst du das bei dir nochmal?
Spricht etwas dagegen, die short_description im Standard im Checkout anzeigen zu lassen?

**Comment by therouv** [comment]
Spricht meines Erachtens nach nichts dagegen.

**Comment by riconeitzel** [comment]
> Funktioniert bei mir, ich habe es gefunden. In den Attributeigenschaften kann man "Sichtbar im Bestellprozess" (is_visible_on_checkout) aktivieren. @riconeitzel: Prüfst du das bei dir nochmal?

geht doch - keine Ahnung, was das war. Tut mir leid.

Liebe Grüße
 Rico
