### ISSUE TITLE
MwSt./USt. Berechnung :: §3 UstG

### ISSUE THREAD

**Issue by scandic** [firegento/firegento-germansetup#137]
Die derzeitige Umsetzung bei den Steuerklassen ist leider zu statisch. Wenn Lieferungen in ein EU-Land eine gewisse Lieferschwelle übersteigen, so muss der Händler die MwSt. des Ziellandes ausweisen und diese auch an die Finanzbehörden des jeweiligen Landes abführen. Außerdem kann ein Händler dies auch freiwillig machen, ohne die Lieferschwelle zu übersteigen.

Mehr zu dem Thema unter http://de.wikipedia.org/wiki/Versandhandelsregelung 

Eine entsprechende Aktivierung der USt-Berechnung nach dem Bestimmungslandprinzip müsste pro Land erfolgen, da vermutlich kein Magentoshop der Welt in allen Ländern der EU ausreichend Umsätze erzielt, um den Verwaltungsoverhead zu rechtfertigen. Außerdem sollte einstellbar sein, ob der ursprüngliche Bruttopreis beibehalten wird oder eine Neuberechnung erfolgt.

Solltet ihr euch entscheiden die Problematik anzugehen, könnte man das Modul eigentlich auch gleich zum Firegento-EUSetup erweitern, da es dann für alle EU-Länder Sinn macht ;)

**Comment by avstudnitz** [comment]
Duplicate of #120 (closed).
