### ISSUE TITLE
E-Mail Import klappt nicht?

### ISSUE THREAD

**Issue by danielrona** [firegento/firegento-germansetup#139]
Hallo,
wir hatten vorher die MRG Installation haben diese nun de-installiert und GS installiert.

Hat alles super geklappt, bisher nichts gefunden was Probleme macht bis auf den E-Mail Import wo anscheinend gar nichts sich verändert hat.

Denn die Mails sehen alle noch so aus wie MRG diese erstellt hatte, nur halt das eine menge leerer Felder dabei sind.

Habe ich evtl. was vergessen? Über jede Hilfe bin ich dankbar.

Magento 1.7.0.2
German Setup: 1.1.4

**Comment by avstudnitz** [comment]
Hallo,
die Email-Templates sollten gelöscht werden, anschließend können sie über das GermanSetup-Formular neu erstellt werden. Email-Templates löschen oder überschreiben wir grundsätzlich nicht, da diese bearbeitet worden sein können.

**Comment by danielrona** [comment]
Super, danke für die schnelle Hilfe!
