### ISSUE TITLE
Checkout agreement lässt sich nicht auf required stellen

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-germansetup#142]
Ich kann im Magento Backend bei den checkout agreements beide von GermanSetup angelegte Agreements sehen aber nicht den Wert **required** auf **true** setzen. Auch habe ich in der Datenbank im der Tabelle **checkout_agreements** keine Spalte **is_required** (die ja mit mysql4-upgrade-1.1.2-1.1.3.php angelegt werden sollte).
Ich habe das jetzt an zwei Shops getestet. Kann das jemand als allgemeines Problem verifizieren oder ist das ein lokales Problem bei mir.

**Comment by grossmann** [comment]
Da die column 'is_required' fehlt werden bei mir folgende exceptions in **var/log/exception.log** gemeldet.

``` php
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_required' in 'where clause'' in /var/www/web/dev-magento/lib/Zend/Db/Statement/Pdo.php:228
```

``` php
Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_required' in 'where clause'' in /var/www/web/dev-magento/lib/Zend/Db/Statement/Pdo.php:234
```

Dadurch lässt sich z.B. der Bezahlprozess nicht durchführen. Ich weiß nicht, warum das vorher noch funktioniert hat. Mit GermanSetup 1.1.4 geht es auf jeden Fall nicht mehr.

**Comment by mklooss** [comment]
welche Magento Version nutzt du???

**Comment by grossmann** [comment]
1.7.0.2

**Comment by grossmann** [comment]
Also nach einige Test hat sich gezeigt, dass meine Installationen die Upgrades von 1.1.2-1.1.3 und 1.1.3-1.1.4 **nicht** durchgeführt haben. In einer weiteren Testinstallation wurden diese jedoch beim Modul-Upgrade von 1.1.2 nach 1.1.4 korrekt ausgeführt. Der Code funktioniert also. Warum das bei meine zwei anderen Installationen nicht ging ist mir nicht klar, da in der DB in 'core_resource' für 'germansetup_setup' der Wert '1.1.4' gesetzt war. Ich habe diesen manuel auf '1.1.2' zurück gesetzt und nach einem page reload sind jetzt alle upgrades vorhanden.
War also vermutlich ein lokales Problem (wenn ich auch nicht weiss warum). -> Deshalb closed
