### ISSUE TITLE
system=> german setup=> setup    no save possibility 

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-germansetup#147]
system=> german setup=> setup    no save possibility 

I want to save  overwritten tax configuration  but  there is no save possibility

**Comment by avstudnitz** [comment]
On the top right, there is a button named "Run German Setup".
If it is not, please provide a screenshot of the whole page including URL.

**Comment by ghost** [comment]
Yes there is a button

but what if want to change the configuration  and then save it

for example  to check out the overwrite possibility and then save

Thanks
Eran

**Comment by avstudnitz** [comment]
Sorry, I don't understand what you want/need.

**Comment by ghost** [comment]
OK

I will try to explain  the issue in a better way

I installed  the   German setup and it is a wonderful extension

now, I go to    system=> German setup=>setup  the next step  I try to
 change the configuration

for example I change the tax settings    and the email settings,    next
step I  try to save my changes with the "Run German Setup" button

but when I press this button  it  doesn't look like he saved the setting,
its look like it came back to its default mode

I hope you can understand  the issue
Thanks

**Comment by therouv** [comment]
If you clock "Run German Setup", it doesn't save the chosen settings but reset the form fields to the default values. Your setup was run with your chosen settings though.
