### ISSUE TITLE
Speicherort der Email-templates

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-germansetup#149]
Hallo,
wo werden denn die templates gespeichert?

**Comment by sprankhub** [comment]
Ich glaube unter `app/locale/de_DE/template/email/`, siehe https://github.com/riconeitzel/German_LocalePack_de_DE/tree/preview/app/locale/de_DE/template/email

**Comment by ghost** [comment]
Hallo,
ja, das dachte ich auch.
Ich hatte mal das Market Ready Modul vor firegento installiert und wieder deinstalliert.
Leider werden zur Auswahl der templates im Adminbereich nur diese alten  templates angezeigt.
Auch wenn ich firegento neu installiere und die templates erstellen lasse, kann ich sie nicht auswählen. 
Wenn ich den Ordner: ...template/email leere, werden sie auch nicht neu geschrieben.

**Comment by easyMaxi** [comment]
Ich habe eigentlich die Option immer auf "Standardvorlage der Lokalisierung" stehen, wenn ich nicht etwas abgeändert habe. Funktioniert das bei dir?

**Comment by ghost** [comment]
diese Option habe ich nicht.

**Comment by sprankhub** [comment]
Dann eventuell statt dem master branch mal den development branch ausprobieren?

**Comment by riconeitzel** [comment]
Die wurden doch afaik in die Datenbank kopiert, oder? Kannst Du mal schauen, ob die Templatenamen doppelt vorkommen oder ggf. die aus der Datenbank mal löschen?

**Comment by ghost** [comment]
die tempate Namen sind nicht doppelt. Was mich stutzig macht ist, dass es auch noch den Ordner: template/email gibt.
Diesen kann man eigentlich dann löschen, wenn die templates in die DB geschrieben werden.

**Comment by mklooss** [comment]
auf keinenfall sollte man die LÖSCHEN.
Diese dienen als "Template" für die E-Mails im Backend.

Bspw. werden die geladen, wenn du auf "Vorlage laden" klickst.

Das sind die Originalen aus dem German_Locale Paket

**Comment by ghost** [comment]
ok, danke für den Tipp.

Grüße
Gerdi
