### ISSUE TITLE
German Setup Variablen

### ISSUE THREAD

**Issue by Baecker** [firegento/firegento-germansetup#150]
Hallo zusammen,

wo finde ich eine Liste der verfügbaren Variablen in German Setup. Hab schon ein paar zusammengetragen (ceo, shop_name, bussiness_rules...), aber es gibt sich mehr davon...

Weiterhin gibt es ja auch Blöcke wie aus address.phtml, communication.phtml...

**Comment by mklooss** [comment]
schau in die system.xml
general/imprint dann dort die fields

das sind die "Variablen" die zur verfügung stehen
