### ISSUE TITLE
Kompatibilität zu Modul "Belvg CallForPrice"

### ISSUE THREAD

**Issue by ThomasKirst** [firegento/firegento-germansetup#154]
GermanSetup und die "Belvg CallForPrice" Erweiterung funktionieren nicht zusammen. Beide erweitern die Core-Klasse "Mage_Catalog_Block_Product_Price".

Im Source von 'FireGento_GermanSetup/app/code/community/FireGento/GermanSetup/Block/Catalog/Product/Price/Abstract.php' könnte man zusätzlich folgende Weiche einbauen.

``` php
} elseif (Mage::getConfig()->getModuleConfig('Belvg_CallForPrice')->is('active', 'true')) {
    abstract class FireGento_GermanSetup_Block_Catalog_Product_Price_Abstract
        extends Belvg_CallForPrice_Block_Catalog_Product_Price { }
}
```

Dieser Issue ist verwandt mit #24.

**Comment by therouv** [comment]
Hallo, ich habe es gerade einmal in Commint 9a8c90a hinzugefügt. Evtl. kannst du es ja einmal mit dem Modul testen und uns ein Feedback geben, ob es nun funktioniert.

**Comment by riconeitzel** [comment]
Hey Rouven, ist der Extend-Check was, was ins Default sollte?! Abhängigkeiten zu anderen Modulen gäbe es ganz schön viele … und Bellvg_CallForPrice klingt jetzt nicht nach etwas, was Standard ist, oder hab ich was übersehen?

**Comment by therouv** [comment]
Hey Rico,

haben wir für das Sitewards_B2BProfessional auch gemacht. Kenne noch andere, die das Belvg_CallForPrice Modul nutzen (auch wenn es kommerziell ist). Von dem her glaube ich schon, dass es Sinn macht.

**Comment by ThomasKirst** [comment]
Hallo Rouven

Vielen Dank für den Change. Funktioniert prima für mich.
