### ISSUE TITLE
Recommended Extensions | NoState

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#158]
Hi!

"NoState - Bundesland/Kanton entfernen"

Dies sollte nur bei älteren Magento Versionen angezeigt werden. In neuen führt das Modul zu Problemen. Zwischenzeitlich ist es ja möglich Magento so zu konfigurieren, dass das Bundesland von Haus aus nicht angezeigt wird -> evtl. könnte aber diese Konfig aufgenommen werden.

**Comment by mklooss** [comment]
die Recommended Extensions ist schon raus im Dev:
https://github.com/firegento/firegento-germansetup/commit/e88235b9b8f2f4d3121ca56526011e94736bb94e

**Comment by daim2k5** [comment]
Denke @mklooss hat recht. Wenn doch eine andere Lösung angestrebt werden sollte macht hier einfach nochmal auf.
