### ISSUE TITLE
Steuerberechnung basiert auf "Versandadresse"

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#16]
Die MwSt Berechnung sollte auf der Versandadresse basieren.

Default ist "Rechnungsadresse"

**Comment by therouv** [comment]
Gibt es dafür rechtliche Vorschriften?

**Comment by mklooss** [comment]
Finde leider gerade keine, wurde uns aber von mehreren Kunden bestätigt die von AT nach DE oder Umgekehrt Versenden.
An dieser Stelle geht es wohl um den Zoll, da das Produkt durch einen Händler ins neue Land geliefert wird.
Und ein Lieferschein bei liegen muss.

**Comment by therouv** [comment]
Meines Wissens nach gibt es hier so viele Feinheiten die man bedenken muss, dass man das ggf. einmal von einem Steuerberater prüfen lassen müsste, ob es hier eine allgemeingültige Vorschrift gibt. 

Prinzipiell hört sich das für mich aber eher nach einer kundenspezifischen Einstellung an. Würde ich eher also aus GermanSetup rauslassen.

**Comment by mklooss** [comment]
Ist auch wieder richtig, man soll dem Shopbetreiber auch nicht zu viel vorkauen :)
Und es ist ja Schnell umkonfiguriert

**Comment by therouv** [comment]
Gut, dann schließen wir das Issue vorerst einmal. Bei Bedarf können wir es dann wieder öffnen.
