### ISSUE TITLE
Dokumentation aller Features

### ISSUE THREAD

**Issue by therouv** [firegento/firegento-germansetup#163]
Wir sollten eine Dokumentation von allen Features des Moduls erstellen, quasi eine Art Handbuch, da auf MC immer wieder Fragen gestellt werden, wie etwas geht.

**Comment by avstudnitz** [comment]
Ja, habe ich schon länger vor, sowas als Blogbeitrag zu machen. Lass uns bei der MM darüber sprechen.

**Comment by riconeitzel** [comment]
Ihr wollt's ja GANZ DICKE :D – ich bin dabei!

**Comment by tobi-pb** [comment]
Ich mach auch mit :-)

**Comment by therouv** [comment]
Cool wäre es, wenn wir alle Features als Markdown schreiben und dann damit z.B. eine PDF-Datei draus generieren :-)

**Comment by davidak** [comment]
ReST ist Markdown für die Dokumentation von Quelltext überlegen. Markdown ist gut für einfache Aufgaben wie Blogs oder Webseiten.

Für die Generierung einer Dokumentation in HTML und auch LaTeX (PDF) gibt es Sphinx.
Wird oft bei Python-Projekten eingesetzt, da es selbst in Python geschrieben ist, aber auch bei einigen PHP-Projekten wie z.B. ownCloud.

http://sphinx-doc.org/
http://www.python.org/doc/
http://doc.owncloud.org/server/6.0/admin_manual/

**Comment by avstudnitz** [comment]
Für das Nachfolgeprojekt MageSetup haben wir die Liste übrigens vor ein paar Wochen erstellt, natürlich mit Markdown :-) Siehe https://github.com/firegento/firegento-magesetup/blob/master/docs/features/features.markdown.
