### ISSUE TITLE
Blank Page with 1.8.0.0-alpha1

### ISSUE THREAD

**Issue by scandic** [firegento/firegento-germansetup#167]
Menu appears but both items result in a blank area (but admin frame is visible).
PHP is 5.4.16 running on FreeBSD with OPCache disabled. No log entries with E_ALL.

Tried both Master & Development branch.

![bildschirmfoto 2013-06-13 um 23 40 14](https://f.cloud.github.com/assets/2125228/651348/f747b0cc-d471-11e2-8a3d-0e3f2ee8e856.png)
![bildschirmfoto 2013-06-13 um 23 40 26](https://f.cloud.github.com/assets/2125228/651349/f74d9168-d471-11e2-966f-6d32a62886d2.png)

**Comment by mklooss** [comment]
can you take a look at the server and magento log files.

**Comment by simontunnat** [comment]
Same here. Magento doesn't display any exceptions.

Update:
From the system log:
2013-06-18T08:59:53+00:00 CRIT (2): Not valid template file:adminhtml/default/default/template/germansetup/notifications.phtml
2013-06-18T08:59:53+00:00 CRIT (2): Not valid template file:adminhtml/default/default/template/germansetup/form.phtml

**Comment by sprankhub** [comment]
Do you use modman? If yes, make sure that symlinks are allowed for template files under System - Configuration - Developer - Template Settings (or something like that).

**Comment by simontunnat** [comment]
Oh you are right. I forgot to update the setting in my test installation.

The extension works fine now!
