### ISSUE TITLE
Anzeige %s MwSt - StoreViews

### ISSUE THREAD

**Issue by Kenzoo79** [firegento/firegento-germansetup#172]
Nach dem Update von <strong>GermanSetup 1.1.4 auf 1.2.3</strong> wird der Platzhalter %s MwSt in der zweiten Store-View nicht mehr korrekt ausgegeben.

<strong>B2C View (Standard)</strong>
Inkl. 19% MwSt., zzgl. Versandkosten
<strong>B2B View</strong>
Zzgl. %s MwSt., zzgl. Versandkosten

**Comment by avstudnitz** [comment]
@Kenzoo79 Warum geschlossen?

**Comment by Kenzoo79** [comment]
@avstudnitz Mir schien als stände ich mit diesem Problem nach dem Update eher alleine da und ich brauchte eine schnelle Lösung für unser Produktivsystem.
Um von einem Downgrade abzusehen, habe ich mir die price_info.phtml aus der Version 1.1.4 genommen über den local Pfad überschrieben, dazu noch die Änderung in der FireGento_GermanSetup.csv und es funktioniert so erstmal wieder. Ich weiß das es nicht unbedingt die beste Lösung ist.
Ich setze das Thema mal wieder auf offen, vielleicht findet sich da noch eine elegantere Lösung.

**Comment by MoniaM** [comment]
Du bist nicht alleine da habe das gleiche Probleme :-( Leider

**Comment by Commercers** [comment]
Mir geht es genauso. Problem stellt sich nur bei der B2B - also Frontend Anzeige exkl. MwSt.
Ich habe nun auch - wie Kenzoo79- die alte price_info.phtml genommen und die locale angepasst (<code>Excl. %s Tax, excl. <a href=""%s"">Shipping Cost</a>","zzgl. %s MwSt., zzgl. <a href=""%s"">Versandkosten</a></code>) Ich habe die quick & dirty Möglichkeit auch bei uns im Blog beschrieben: http://www.commercers.com/blog/

**Comment by Jorsan** [comment]
Hallo,
bei mir ist die Anzeige nach dem Update auch falsch!

Zzgl. %s MwSt., zzgl. Versandkosten

zusehen auf:
www.dema-handel.de

....wird dies beim nächsten Update geändert?
gruß Michi

**Comment by avstudnitz** [comment]
Ist jetzt im development-Branch behoben. Bitte um Test.

**Comment by Jorsan** [comment]
Ja, habe es getestet und funktioniert!

www.dema-handel.de
