### ISSUE TITLE
email template Textformatierung

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-germansetup#184]
Hallo,

wo kann man denn den Summenblock im der Bestellmail formatieren? In der Vorlage ist nichts. Die Schriftart des Block total ist viel zu groß.

**Comment by avstudnitz** [comment]
Schau dir mal den Block "<sales_email_order_items>" in der Datei /src/app/design/frontend/base/default/layout/sales.xml an. Hier sind die einzesetzten PHTML-Dateien aufgeführt, sowie ein paar CSS-Anweisungen.
