### ISSUE TITLE
'Zzgl. %s MwSt..' bei Netto Preis

### ISSUE THREAD

**Issue by juhulian** [firegento/firegento-germansetup#186]
Hey!
wenn man im frontend sich den Nettopreis anzeigen lässt,
kommt es zu einem Fehler in der Anzeige. 
Beispiel:  
5,19 Fr. Zzgl. %s MwSt., zzgl. Versandkosten
bzw.:
4,21 € Zzgl. %s MwSt., zzgl. Versandkosten

Viele Grüße
Juhulian

**Comment by avstudnitz** [comment]
Ist mit #172 im Development-Branch behoben.
