### ISSUE TITLE
Agreements Anpassungen greifen nicht bei PayPal Express

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-germansetup#189]
Die Anpassungen der Agreements (https://github.com/firegento/firegento-germansetup/blob/development/src/app/design/frontend/base/default/layout/germansetup.xml#L462) greifen nicht bei Nutzung der PayPal Express Zahlungsart. Denn das ist eine komplett andere Review-Seite mit anderem Handle (`paypal_express_review`) und anderem Template (`paypal/express/review.phtml`). Wenn ich das richtig sehe, sollten die GermanSetup Änderungen aber auch da greifen.

**Comment by mklooss** [comment]
PayPal nutzt ein komplett eigenen Controller, daher der Unterschied:
http://svn.magentocommerce.com/source/branches/1.8/app/design/frontend/base/default/layout/paypal.xml

**Comment by sprankhub** [comment]
Moved to MageSetup (https://github.com/firegento/firegento-magesetup/issues/28).
