### ISSUE TITLE
Problem beim Hinzufügen eines neuen Steuersatzes 

### ISSUE THREAD

**Issue by markluebcke** [firegento/firegento-germansetup#190]
Wenn ich beispielsweise für Albanien einen neuen Steuersatz hinzufügen möchte, erhalte ich eine Fehlermeldung, dass der Steuersatz schon existiert.

**Comment by riconeitzel** [comment]
Steuersatz einfach anders nennen oder die Steuerkonfiguration mit der aktuellsten Version neu überschreiben lassen, da ist der Bug behoben.
