### ISSUE TITLE
meta-autogenerate

### ISSUE THREAD

**Issue by kilianyp** [firegento/firegento-germansetup#192]
Hey,

so the "german setup" itself works fine, however, I am trying to use the Auto-meta generate function as well. 
I import my products using magmi (Magento Mass Importer) and set the attribute auto_metagenerate to 1. If I check the product after the import, the auto-metagenerate attribute is set to yes, but there is no text generated. Only when I click on save, the text gets generated. This means I would need to save every single product to generate the meta-texts. Indexing and caching didn't help either. 

Is there any way to force magento to create those meta-tags?

Thanks

Edit1: Ich verstehe auch deutsch!

**Comment by mklooss** [comment]
how did you import the data, with ImportExport?
Autogen for Meta Tag is only a Event in the Save Observer:
https://github.com/firegento/firegento-germansetup/blob/master/src/app/code/community/FireGento/GermanSetup/etc/config.xml#L90

https://github.com/firegento/firegento-germansetup/blob/master/src/app/code/community/FireGento/GermanSetup/Model/Observer.php#L114

**Comment by kilianyp** [comment]
Hello,

thanks a lot for your response. I used Magmi (Magento Mass Importer) for 
import. Stupid me didn't realize at first that I could just extract the 
meta data from my database and use Magmi to import it.
So problem is already solved, but I really appreciate your time.

Thanks,
kilsen512
