### ISSUE TITLE
Lieferzeit Anzeige auf Produktseite abschalten

### ISSUE THREAD

**Issue by qx54** [firegento/firegento-germansetup#193]
Wie kann ich die Anzeige der Lieferzeit auf der Produktseite abstellen?

Wäre froh, wenn ich da schnell eine Antwort erhalten, denn wie ich sehe werden die meisten meisten Issues monatelang nicht beantwortet.

Danke und Gruss

**Comment by riconeitzel** [comment]
In deiner local.xml

```
    <default>
        <remove name="magesetup.deliverytime" />
    </default>
```

**Comment by qx54** [comment]
Besten Dank.

In meinem Fall war es:

```
<default>
    <remove name="germansetup.deliverytime" />
</default>
```
