### ISSUE TITLE
Code assign phpDoc @var

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#199]
Moin

mir ist aufgefallen, das häufig im Code folgendes Schema vorhanden ist.

```
/**
 * @var $this Mage_Checkout_Block_Cart_Shipping
 */
```

Dieses wird aber von vielen IDEs nicht unterstützt, da der Syntax falsch ist.
Es kein Bestandteil von phpDoc oder apiGen ist, in phpDoc ist es für die Klassenvariablen

Der Syntax müsste eigentlich folgender sein:

```
/* @var $this Mage_Checkout_Block_Cart_Shipping */
```

http://www.phpdoc.org/docs/latest/for-users/phpdoc/tags/var.html

Der Syntax selber kommt vom Zend Studio:
http://files.zend.com/help/Zend-Studio/zend-studio.htm#working_with_code_assist.htm

Ich weiss das es etwas kleinlich ist :)

**Comment by sprankhub** [comment]
Mir ist das relativ wurscht, weil PhpStorm beides kann :-) Wenn es dich stört, könntest du einen Pull Request für MageSetup machen, der das behebt ;)
Da GermanSetup nicht weiter entwickelt wird, würde ich vorschlagen, das Issue hier zu schließen.

**Comment by Schrank** [comment]
Ich bin mal so frech. Und ich unterstütze den Vorschlag, einfach korrigieren und ab in MageSetup rein.

**Comment by mklooss** [comment]
@sprankhub alles klar, werde ich die Tage dann bei MageSetup mal machen ^^...
