### ISSUE TITLE
Steuerberechnung in Magento 1.8

### ISSUE THREAD

**Issue by timop-mug** [firegento/firegento-germansetup#202]
Hallo,

folgendes Problem:
Neue Bestellung, ein Artikel im Warenkorb:

![bildschirmfoto_2013-11-11_um_15 23 40-2](https://f.cloud.github.com/assets/3283401/1513175/1a305ec2-4add-11e3-8e91-21211c34d4cf.png)

Wie euch sicher auffällt kann da mit der Berechnung etwas nicht stimmen.
Egal wie, ich komme nicht drauf was das gerechnet wird.

Im Backend sieht das Ganze so aus:

![bildschirmfoto 2013-11-11 um 15 27 15](https://f.cloud.github.com/assets/3283401/1513204/b65e9f48-4add-11e3-9160-5c8b76cef3dc.png)

7% Steuer: 3,20 €
Gesamtbetrag Steuern: 3,25 €

davon abgesehen, dass keiner der Zahlen korrekt ist, ist mir schleierhaft wo er die 5 Cent hernimmt.

**Comment by Schrank** [comment]
Mein Tipp: Rundungsfehler der Steuern. Probier es nochmal mit einem Artikel der 41,40 kostet oder stell die Berechnung der STeuern im Backend um-

**Comment by riconeitzel** [comment]
Ich schätze auch, dass die Steuerberechnung statt auf Gesamt auf Einzelpreis steht.

Liebe Grüße
 Rico

**Comment by timop-mug** [comment]
Bringt auch ein falsches Ergebnis:
![bildschirmfoto 2013-11-11 um 15 41 21](https://f.cloud.github.com/assets/3283401/1513318/7c655da2-4adf-11e3-9f1f-793ba9ba4d33.png)

Die Steuern der Versandkosten werden schon falsch berechnet.
Bei Magento 1.8 wurde doch etwas an der Steuerberechnung verändert, kann es vielleicht damit zusammenhängen?

**Comment by timop-mug** [comment]
Alle Preise sind inkl. Steuern hinterlegt,
![bildschirmfoto 2013-11-11 um 15 59 54](https://f.cloud.github.com/assets/3283401/1513440/f6c5a44c-4ae1-11e3-8607-a84aa6a59395.png)

Und zum Test wurde jetzt "Dynamische Berechnung der Versand-Steuerklasse" auf "No dynamic shipping tax calculation" gestellt.
Steuerklasse für den Versand: Ermäßigtbesteuerter Versand

**Comment by riconeitzel** [comment]
Stell mal die Option: "Kundensteuerklasse Anwenden" auf "Vor Rabatt" um bitte!

**Comment by timop-mug** [comment]
Hab ich, keine Änderung.
Er rechnet die Steuer auf den Versand nicht auf Basis von 7,50€ sondern nur auf 7€. Also das würde die 0,49 € Steuern auf Versand erklären. Bleibt noch offen, warum er das macht.

**Comment by riconeitzel** [comment]
Bei 7% hat man 7 netto bei 7,50 brutto...

Könnte es daran liegen?

**Comment by timop-mug** [comment]
Ehm ja, macht Sinn.
Aber Magento rechnet jetzt die Gesamtsumme der Steuern richtig aber summiert dann in der Auflistung der Steuersätze die richtige Steuersumme der ganzen Bestellung inkl. Versandsteuern nochmal die Steuern für den Versand. 
Lade nachher in der Agentur einen Screenshot hoch. 

Gesamtsumme inkl Steuer 33,00 €
Steuern Versand: 0,49 €
Steuern Gesamtsumme: 2,16 €
Steuern DE 7% (7,0000%): 2,65 €

**Comment by timop-mug** [comment]
Hier der Screenshot:
![bildschirmfoto 2013-11-12 um 15 25 51](https://f.cloud.github.com/assets/3283401/1522337/6c4a2318-4ba6-11e3-8597-e78f7ad7af6a.png)

Ich verstehe nicht wie Magento auf den Betrag der 7% Steuern kommt. In den 2,16 € sind ja die 7% für den Versand mit drin.

**Comment by antoiovane** [comment]
Hi, I need a Magento plugin that select method payments by customer groups. I'm not very sicure that is the plugin "PaymentFilter for Products and Customer Groups" that resolve my problems...Yes, I need select different methods by customer group but, for example, if  the customer JOHN from GROUP A select Paypal with address pippo@live.it, the customer CATHERINE from GROUP B when select the same payment method must to pay from address salesmiles@hotmail.it ...
So I need select and reply methods by customer groups. Please help me, is urgent!! Thanks.

**Comment by Schrank** [comment]
@antoiovane There are lots of developers out there, most of them have more work, then they can do. Just send an email to a few of them and ask for quotes.

**Comment by timop-mug** [comment]
Kann der Fehler bei der oben genannten 7% Steuer an germansetup liegen?
Ich hab inzwischen ein paar Erweiterungen deaktiviert aber der Fehler bleibt. 
![bildschirmfoto 2013-11-18 um 12 41 40](https://f.cloud.github.com/assets/3283401/1562407/7ebf6ebe-5046-11e3-8f4a-010c99a7a274.png)

**Comment by Schrank** [comment]
Neues Magento aufsetzen, German Setup installieren, Fall nachstellen :)

**Comment by timop-mug** [comment]
Hab ich jetzt mal gemacht. 
Neues Magento 1.8 und nur germansetup installiert.
Bei den 7% wird trotzdem zu der Gesamtsteuer, die die Versandsteuer ja bereits beinhaltet, nochmal die Versandsteuer addiert. 
![bildschirmfoto 2013-11-18 um 14 03 59](https://f.cloud.github.com/assets/3283401/1562820/0c96f2e2-5052-11e3-86c9-2bb4a2e4a597.png)

**Comment by timop-mug** [comment]
Der Fehler scheint erst bei der Rechnung aufzutreten. In der Bestellung stimmt noch alles aber wenn ich dann zur Rechnung wechsele erhöht sich die Teilsteuer:

Bestellung: 
![bildschirmfoto 2013-11-18 um 15 00 59](https://f.cloud.github.com/assets/3283401/1563109/2c948a20-505a-11e3-8e9b-5bc040e49b54.png)

Rechnung: 
![bildschirmfoto 2013-11-18 um 14 03 59](https://f.cloud.github.com/assets/3283401/1563111/35788d26-505a-11e3-839e-6751c336eb63.png)

**Comment by timop-mug** [comment]
Scheint ein Problem von Magento 1.8 zu sein.
Hab nen neues 1.7 aufgesetzt und bekomme das:
![bildschirmfoto 2013-11-19 um 10 15 45](https://f.cloud.github.com/assets/3283401/1571051/520a827c-50fb-11e3-9ee0-892eb0cd920b.png)

**Comment by Galanos** [comment]
Hey, ich darf mich mal einklinken. Habe dasselbe Problem, siehe Screenshots.

Summierungsfeld der Bestellung:
![bildschirmfoto 2013-12-08 um 20 11 47](https://f.cloud.github.com/assets/2743446/1701113/9a566cda-6041-11e3-8907-c08300de396c.png)

Summierungsfeld der Rechnung:
![bildschirmfoto 2013-12-08 um 20 12 40](https://f.cloud.github.com/assets/2743446/1701114/a1fda30e-6041-11e3-8522-98c7027cdf2d.png)

Seid ihr zufaellig schon auf einen Ursprung oder gar auf eine Loesung gekommen? Bin fuer Hinweise dankbar.

**Comment by timop-mug** [comment]
Nein leider nicht, es liegt aber nicht an germansetup.
Bis es ne Lösung gibt, sind wir wieder auf 1.7 zurück.

Es findet sich im Netz auch nicht wirklich was darüber.

**Comment by Schrank** [comment]
Ich hätte noch ne These, aber leider nicht die Zeit sie zu prüfen.

Magento sortiert ja die Totals (die die Steuern berechnen) nach `<after>` und `<before>` statements der einzelnen totals. Magento hatte schon immer einen Bug und hat nicht ordentlich sortiert, mit ein paar mehr Totals im before und after konnte man das fixen. Eventuell liegt es daran. Prüft mal, ob die Summen, auf deren Basis die Steuern berechnet werden stimmen. Alternativ könnt ihr euch einfach die `Sales/etc/config.xml` anschauen und mal ein paar before und after dazu tun, das könnte das problem lösen. Die Anzeige im Frontend (cart, review) kann man super zum Testen nehmen, Shipping auswählen und dann zurück in den Cart, dann muss man nur noch F5 drücken.

**Comment by Galanos** [comment]
Danke fuer die Hinweise.

@timop-mug Ich fuerchte, es werden nicht nur einfach die Steuern auf Versandkosten nochmals drauf addiert, das duerfte ein … False Positive in deinem Fall gewesen sein. Bei meinem Beispielfall betraegt die Steuer auf Versandkosten 0,78 €, die Differenz zwischen erwarter und effektiver Gesamtsteuer ist jedoch 3,92 €.

Mein Entwickler ist leider nicht erreichbar, habe deshalb nur mal nach den Unterschieden in der sales/etc/config.xml zwischen 1.7 und 1.8 geschaut. Laesst vermutlich bei niemandem die Alarmglocken schrillen, oder?

In Linien 625-630 _hinzugekommen_ in 1.8:

```
                <discount_description>
                    <to_invoice>*</to_invoice>
                </discount_description>
                <discount_description>
                    <to_cm>*</to_cm>
                </discount_description>
```

In Linie 1452 _geaendert_ in 1.8 (Minuszeichen zwischen Tags entfernt):

```
                    <amount_prefix></amount_prefix>
```

In Linie 1453 _hinzugekommen_ in 1.8:

```
                    <title_source_field>discount_description</title_source_field>
```

In Linie 1587 _ersatzlos entfernt_ in 1.8:

```
            <catalogrule_before_apply>
                <observers>
                    <sales_quote_observer>
                        <class>sales/observer</class>
                        <method>markQuotesRecollectOnCatalogRules</method>
                    </sales_quote_observer>
                </observers>
            </catalogrule_before_apply>
```

**Comment by Galanos** [comment]
Hat schon jemand die frische 1.8.1.0 ausprobiert und geschaut, ob das Problem geloest wurde?

**Comment by magentinchen** [comment]
Magento 1.8.1.0 behebt das Problem. Ursache war, dass die Versandsteuer im Tax helper (getCalculatedTaxes) in einer Schleife pro Artikel addiert wurde, was jetzt vor die Schleife gezogen wurde.

**Comment by caos989** [comment]
Hi

Ich habe Magento 1.8.1.0 und habe auch das Problem dass die Steuer in der Rechnung falsch berechnet wird. In der Bestellung wird sie aber richtig berechnet.

Ich habe 10%ige und 20%ige Artikel (Österreich) in meinem Shop. Wenn ein 10% MWST Artikel gekauft wird, so wird der Versand auch mit nur 10% berechnet.

Wisst ihr wo ich den Fehler finde?

**Comment by Galanos** [comment]
@caos989 Ist dieser Punkt bewusst und korrekt eingestellt? _System > Konfiguration > Verkaeufe > Steuer > Steuerklassen_

![bildschirmfoto 2014-02-09 um 23 15 48](https://f.cloud.github.com/assets/2743446/2121192/e764d38c-91d7-11e3-873f-e692e011dc9b.png)

**Comment by caos989** [comment]
Dieser Punkt ist bei mir nicht sichtbar. Ich kann nur die Steuerklasse auswählen.
![screen-01](https://f.cloud.github.com/assets/6633686/2121229/0ecc5d36-91d9-11e3-8c03-34825dc39d45.JPG)

**Comment by Schrank** [comment]
Welche version von germansetup ist bei dir installiert? Evtl über ein update auf magesetup nachdenken.

**Comment by caos989** [comment]
Ich habe    2.1.40 (stable) wobei ich factfinder gelöscht habe weil dieser probleme verursacht hat.

**Comment by Schrank** [comment]
Dann redest du von Market Ready Germany und bist hier leider falsch.

Ich weiß leider auch nicht wer oder wo es Support dafür gibt.

**Comment by fjratelier** [comment]
Hallo,
ich habe gestern den Firegento German Setup installiert. Bis jetzt alles ok, nur dass ich jetzt bei der onepage checkout zwei Bestellübersichten habe. Einer von German Setup und eine andere von Magento selbst, wisst Ihr, wie ich das beheben kann? Meine Version ist die 1.8.0.1 Hier noch ein kleines screenshot damit ihr sehen könnt was ich meine, danke.
http://screencast.com/t/z7dfswperOp

**Comment by riconeitzel** [comment]
Hallo,

die Entwicklung von GermanSetup wurde zu Gunsten https://github.com/firegento/firegento-magesetup eingestellt. Bitte verwende nur noch MageSetup und nicht mehr GermanSetup.

Die Umstellung erfolgt allein durch Austausch der Dateien, da MageSetup von GermanSetup abstammt.

Sollte der Fehler weiterhin auftreten, suche Bitte bei https://github.com/firegento/firegento-magesetup/issues nach einer bestehenden Meldung, die zu Deinem Problem passt. Vielleicht findest Du dann bereits die Antwort. Andernfalls stell bitte dort deine Fehlermeldung nochmal ein.

Danke und viele Grüße
 Rico
