### ISSUE TITLE
CMS-Blöcke werden nicht ausgeführt (Magento 1.8)

### ISSUE THREAD

**Issue by Summit-Design** [firegento/firegento-germansetup#203]
Nach update auf Magento 1.8 werden in meinem Impressum und Transaktion emails die imprint Angaben nicht mehr ausgeführt bzw. die Werte/Angaben erscheinen nicht mehr im Imprsssum und den emails.

{{block type="germansetup/imprint_content" template="germansetup/imprint/address.phtml"}}

{{block type="germansetup/imprint_content" template="germansetup/imprint/communication.phtml"}}

{{block type="germansetup/imprint_content" template="germansetup/imprint/legal.phtml"}}

{{block type="germansetup/imprint_content" template="germansetup/imprint/bank.phtml"}}

{{block type="germansetup/imprint_field" value="business_rules"}}

Bin für jeden Hinweis dankbar!
Beste Grüße
Thomas

**Comment by mklooss** [comment]
haste schon mal ins Log geschaut, da es bei mir keine Probleme gibt...
also system.log etc?

ggf steht es dort drin.

**Comment by Summit-Design** [comment]
Danke für den Hinweis! 
Konnte das Problem lokalisieren und beheben!

Beste Grüße
Thomas
Am 13.11.2013 um 21:07 schrieb Mathis Klooß notifications@github.com:

> haste schon mal ins Log geschaut, da es bei mir keine Probleme gibt...
> also system.log etc?
> 
> ggf steht es dort drin.
> 
> —
> Reply to this email directly or view it on GitHub.

..............................................................
Thomas Witt
Luegallee 72
40545 Düsseldorf

0151- 46320195
witt@summit-design.eu

www.summit-design.eu

**Comment by BrocksiNet** [comment]
In Magento 1.13. / ggf. auch in 1.8 wird der Block {{block type="germansetup/imprint_content" template="germansetup/imprint/email_footer.phtml"}} im Backend bei der Vorschau von Transaktions-Emails nicht gefunden. Das liegt daran das das Template nicht in app\design\adminhtml\default\default\template\germansetup\imprint\email_footer.phtml hinterlegt ist.

**Comment by mklooss** [comment]
@bjoern-flagbit das ist meine ich schon immer so...
und die Vorschau ist so wieso nicht wirklich geeignet, da bspw. bei den Order Mails etc die Infos Fehler usw.

**Comment by BrocksiNet** [comment]
Mag sein, nur hilft ein WSD auch nicht weiter ;-) Falls man mal eine bestimmte E-Mail sucht.

**Comment by sprankhub** [comment]
Auch wenn ggf. bekannt möchte ich hier mal auf die EmailPreview Extension vom Hackathon aufmerksam machen :-) https://github.com/magento-hackathon/E-MailPreview

**Comment by winkelsdorf** [comment]
Hatte bei einem Kunden kürzlich auch dieses Problem. Um nicht die fertigen E-Mail-Templates und CMS Seiten zu verlieren, hab ich einfach in einem DB Dump nach 'germansetup' gesucht.

Abgesehen von den Werten in den Core Tabellen, die lediglich dazu dienen, die Ausgabe von GermanSetup abzuschalten und den Installationsstatus zu setzten (*), finden sich die Variablen in den Tabellen 'cms_page' und 'core_email_template'.

Bitte nicht einfach ein Truncate auf die Tabellen machen, da hier Foreign Keys von anderen Tabellen drauf zeigen.

Am einfachsten mit einem Interface wie phpmyadmin nach LIKE %germansetup% in den beiden Tabellen suchen und durch magesetup ersetzten.

Sprich: {{block type="germansetup/... wird zu {{block type="magesetup/...

(*) Dies kann man auch bereinigen. Läuft einwandfrei, so dass alle Überreste von dem alten GermanSetup Modul entfernt sind. Auf dem Webserver ggf. auch noch die Dateien vom GermanSetup entfernen (z.B. im MageConnect Cache).
