### ISSUE TITLE
Zahlart konnte nicht gesetzt werden

### ISSUE THREAD

**Issue by tody12ab** [firegento/firegento-germansetup#207]
Nach der Installation von Firegento in Magento 1.8.1.0 bekomme ich im Onepage Checkout im Schritt "Zahlunsginformationen" die Fehlermeldung "Zahlart konnte nicht gesetzt werden". Hatte jemand ein ähnliches Problem?

**Comment by sprankhub** [comment]
Da GermanSetup nicht mehr weiter entwickelt wird, kann es ggf. sein, dass es mit neueren Versionen (1.8) nicht klar kommt (auch wenn es mich etwas wundern würde, wenn das wirklich an GermanSetup liegt). Wie auch immer, probier es mal mit dem Nachfolger [MageSetup](https://github.com/firegento/firegento-magesetup). Da sollte es keine Probleme geben und wenn doch, helfen die Jungs da bestimmt gerne weiter :-)
