### ISSUE TITLE
Conflict with Amazon Payment

### ISSUE THREAD

**Issue by Waldemar-Denke** [firegento/firegento-germansetup#208]
Hi, at first thx for your Extensions. Firegento is very helpful and i'm happy to use it instead of Market ready.

I'm not sure the problem comes from this extension.

Had installed GermanSetup and updated to MageSetup.

In the Checkout of Amazon Payment: Payment Method Step -> i get this error in the Response (savePayment).

Fatal error: Class 'Mage_Germansetup_Helper_Data' not found in /www/htdocs/w0xxxx/magento/app/Mage.php on line 547

savePayment breaks.

Can't figure out wher it comes from. Have deleted all Files of German Setup.
MageSetup is running correctly. Even when i disable Mage Setup i get this error.

**Comment by Schrank** [comment]
I would guess, somewhere in your extensions the germansetup helper is still called, e.g. from system.config. Theoretically should MageSetup deactivate GermanSetup, inluding all *.xml files. 

Did you refresh the cache? If you provide the complete strack trace, I can have a look but this error only says: "I can't find the helper class" which is logic, if it is deleted and whatever wants to create a helper.

**Comment by mklooss** [comment]
take a look at the Transaction E-Mail

**Comment by Waldemar-Denke** [comment]
I've got it.
had an old agreement template (from germansetup) in checkout/onepage/agreements.phtml

I was able to isolate the problem, thanks for your fast help.
