### ISSUE TITLE
Bundle Product error when Sitewards B2B installed

### ISSUE THREAD

**Issue by thomasklosinsky** [firegento/firegento-germansetup#209]
In newer versions of Extension Sitewards B2B there is no class Sitewards_B2BProfessional_Block_Price anymore 
so result is:
Fatal error: Class 'Sitewards_B2BProfessional_Block_Price' not found in /var/www/app/code/community/FireGento/GermanSetup/Block/Bundle/Catalog/Product/Price/Abstract.php on line 40

Any fix already?

Best,
Thomas

**Comment by Schrank** [comment]
Wow, I didn't even know, there is such a switch. If you need a quick fix, just remove everything from this file and add instead:

```
abstract class FireGento_GermanSetup_Block_Bundle_Catalog_Product_Price_Abstract
    extends Mage_Bundle_Block_Catalog_Product_Price
{

}
```

**Comment by thomasklosinsky** [comment]
Tried that (also before posting here), but running into this error instead:

Fatal error: Class 'FireGento_GermanSetup_Block_Bundle_Catalog_Product_Price_Abstract' not found in /var/www/app/code/community/FireGento/GermanSetup/Block/Bundle/Catalog/Product/Price.php on line 37 

;)

**Comment by Schrank** [comment]
sorry, copied the class name from MageSetup. Updated the post. should be:

```
abstract class FireGento_GermanSetup_Block_Bundle_Catalog_Product_Price_Abstract
    extends Mage_Bundle_Block_Catalog_Product_Price
{

}
```

**Comment by thomasklosinsky** [comment]
Ah, just changed 

abstract class FireGento_MageSetup_Block_Bundle_Catalog_Product_Price_Abstract
    extends Mage_Bundle_Block_Catalog_Product_Price
{

}

to 

abstract class FireGento_GermanSetup_Block_Bundle_Catalog_Product_Price_Abstract
    extends Mage_Bundle_Block_Catalog_Product_Price
{

}

and it works well

**Comment by Schrank** [comment]
This problem is not solved, it is just a quick fix :-)

**Comment by sprankhub** [comment]
Yes, but this will not be fixed in GermanSetup since GermanSetup is not maintained any longer. It will hopefully be fixed in MageSetup. An appropriate issue exists: https://github.com/firegento/firegento-magesetup/issues/41
