### ISSUE TITLE
Falscher MwSt. Satz im List-view und bei den Upsell Products

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#21]
Sehr geehrte Damen und Herren,

zuerst einmal möchte ich Ihnen für das Magento Modul German Setup danken. Ein wirkliches tolles Modul das mir erheblich Zeit erspart hat.

Wir haben in unserem Shop Produkte mit verschiedenen Steuersätzen (7 und 19%).
Ich habe das Modul German Setup installiert und nur den Steuer-Part aktiviert.
Was mir aufgefallen ist:

Im Listview ist nun bei allen Artikeln in der Liste standardmässig 7% aufgelistet obwohl der letzte Artikel 19% hat:
http://www.web412.server3.keller-brennecke.de/esspapier-1.html
Wenn man nämlich auf den letzten Artikel klickt steht dann wieder der richtige Steuersatz drin
http://www.web412.server3.keller-brennecke.de/esspapier-1/monster-esspapier-schlusselanhanger.html

Das selbe Problem auch bei den Upsell Products unten auf dieser Seite (auf verwandte Artikel klicken)
http://www.web412.server3.keller-brennecke.de/esspapier-1/essbare-fussballe-aus-esspapier.html

Es scheint jeweils immer der erste gefundene MwSt-Satz für alle Artikel genommen zu werden.

Ich wäre Ihnen wirklich sehr dankbar, wenn Sie mir hierbei helfen könnten.  

(per Email an avs@avs-webentwicklung.de)

**Comment by avstudnitz** [comment]
Das Problem scheint in der FireGento_GermanSetup_Block_Catalog_Product_Price zu liegen. In der Methode getTaxRate wird $this->_loadTaxCalculationRate($this->getProduct()) aufgerufen, aber anscheinend wird in Listenansichten hier nur das erste Produkt aufgerufen, und nicht das jeweils passende.

**Comment by therouv** [comment]
Habe das Issue entsprechend behoben. Für jedes Produkt wird nun ein individueller Tax Rate Key erzeugt..
