### ISSUE TITLE
GERMANSETUP on my template i have blank page

### ISSUE THREAD

**Issue by blumentaxi** [firegento/firegento-germansetup#210]
i have install german setup on my template magenta 1.7 i have after install blank page in admin panel and frontend please help me..

**Comment by Schrank** [comment]
First tip: Install MageSetup (new version) and not german setup(deprecated)
Second: magento.stackexchange.com/questions/428/fundamentals-for-debugging-a-magento-store

a blank page means, you have debug mode off, therefore you don't see error messages.

**Comment by blumentaxi** [comment]
Hallo Herr fabian

ich habe das neue Modul ausprobiert ich bekomme weiterhin eine weisse Seite angezeigt in admin als auch in frontend.. könntest du mir helfen.

Am 19.02.2014 um 10:27 schrieb Fabian Blechschmidt notifications@github.com:

**Comment by mklooss** [comment]
Ich würde dir dringend empfehlen die Zugangsdaten zu ändern, dieses ist ein Öffentliches System und kann von jedem auf der Welt eingesehen werden!

habe diese gerade per E-Mail erhalten, wie vermutlich einige andere auch.

Zum Fehler es scheint ein Fehler schon tiefer im System zu sein. und eine PHP Fehlermeldung zu sein.
Hier ist es am besten die Server Logs anzuschauen.

**Comment by Schrank** [comment]
Für den Fall, das es jemandem hilft: Compilermode war an, und der nicht aktualisiert, was dazu führt, dass die FireGento Klassen nicht im compiler-dir sind und damit nicht gefunden werden.

**Comment by blumentaxi** [comment]
ok danke nochmals

Am 19. Februar 2014 11:39 schrieb Fabian Blechschmidt <
notifications@github.com>:
