### ISSUE TITLE
Versandkostenlink ohne /

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-germansetup#212]
Hallo,
Der Versandkosten-Link im footer wird mit "/" am Ende ausgegeben, die Versandkostenlinks in den Grids bei den Produkten werden ohne slash ausgegeben. Google meckert da.
Wo und wie kann ich den slash hinzufügen?
/app/design/frontend/base/default/template/germansetup/price-info.phtml???

Gruß

**Comment by Schrank** [comment]
Die frage kann ich leider nicht beantworten, aber was meckert google denn?

**Comment by ghost** [comment]
Google meckert in den WMT, dass er 2 unterschiedliche Links findet.

**Comment by sprankhub** [comment]
Wie immer der obligatorische Hinweis: GermanSetup wird nicht mehr weiterentwickelt, am besten auf [MageSetup](https://github.com/firegento/firegento-magesetup/) updaten.

Der Versandkostenlink wird in zwei Templates ausgegeben, da könntest du den Slash hinzufügen (auch wenn ich den Sinn dieses Vorhabens ehrlich gesagt anzweifel):
- app/design/frontend/base/default/template/germansetup/price_info.phtml
- app/design/frontend/base/default/template/germansetup/shipping.phtml

Natürlich solltest du das in deinem eigenen Package/Theme anpassen.
