### ISSUE TITLE
Issue Bereich schließen?

### ISSUE THREAD

**Issue by daim2k5** [firegento/firegento-germansetup#213]
Und dazu evtl. noch größer darauf hinweisen das man magesetup verwenden sollte?

**Comment by sprankhub** [comment]
+9999999999999999999999999999999999999999999999999999999999999999999

Wobei man eigentlich noch die offenen Issues durchgehen sollte und ggf. zu MageSetup portieren sollte...

**Comment by riconeitzel** [comment]
Wie wäre es mit einem Autoresponder auf einer eigene eMailadresse?

**Comment by sprankhub** [comment]
Wieso nicht einfach schließen?

**Comment by riconeitzel** [comment]
Weil dann die alten Issues alle nicht mehr findbar sind. Außer, jemand migriert das auf eine Website … #itsNotMe

**Comment by daim2k5** [comment]
Wenn nach Monaten eine Issue immer noch offen ist wird diese auch nicht mehr geschlossen.
Also bitte schließt das doch einfach und gut ist. Wird sich keiner beschweren.
