### ISSUE TITLE
In der Kategorie-Ansicht deaktivieren

### ISSUE THREAD

**Issue by hierbeidir** [firegento/firegento-germansetup#214]
Hallo Zusammen,

ist es möglich die Angaben "Inkl. 19% MwSt., zzgl. Versandkosten" und die Lieferzeit nur aus der Kategorie-Ansicht zu entfernen? 

Leider funktioniert der Tip hier nicht mehr:  http://www.magentocommerce.com/boards/viewthread/309049/ 

Vielen Dank und beste Grüße

**Comment by Schrank** [comment]
Ist es möglich? Nein, nicht out-of-the-box.

Da die price.phtml via observer angepasst wird, geht das nicht so ohne weiteres. Das passiert hier `app/code/community/FireGento/MageSetup/Block/Catalog/Product/Price.php`. Du könntest den Observer überschreiben und an der Bedingung basteln, so dass die Info nur auf Produktdetailseiten zu sehen ist.

Ich nehme an du weißt, dass der Hinweis kommen muss, wenn man in der Lage ist, etwas in den Warenkorb zu legen? Und das ist bei euch bestimmt nicht so. - Nur zur Sicherheit :-)

Was du auch machen kannst ist, einen Observer schreiben der auf `magesetup_after_product_price` lauscht und das `html_obj` einfach leer macht, wenn du den Hinweis nicht möchtest.
