### ISSUE TITLE
EORI-Nummer

### ISSUE THREAD

**Issue by JuliaNicky** [firegento/firegento-germansetup#215]
Leider kann ich bei der Erweiterung GermanSetup keine Einstellungsmöglichkeit der EORI-Nummer im Bereich Impressun finden.
Diese muss auf der Rechnung zu sehen sein.

Übersehe ich da etwas?

**Comment by riconeitzel** [comment]
Hey,

bitte verwende nicht GermanSetup nicht mehr. Es wurde von MageSetup (https://github.com/firegento/firegento-magesetup) abgelöst. Ein Umstieg ist durch Austausch der Dateien machbar.

Die EORI-Nummer kann aktuell weder bei Mage- noch bei GermanSetup in einem eigenen Feld eingegeben werden, allerdings hast Du die Möglichkeit, je nach Modul, welches Deine Rechnung erzeugt, diese Nummer in einem Freitextfeld einfach einzutragen. Anschließend sollte sie dann auch in der Rechnung erscheinen.

Liebe Grüße
 Rico
