### ISSUE TITLE
Änderung Widerrufsrecht

### ISSUE THREAD

**Issue by Holger1975** [firegento/firegento-germansetup#216]
Sehr geehrte Damen und Herren,

Am 13. Juni 2014 tritt die neue Verbraucherrechterichtlinie in Kraft.

Wesentliche Punkte sind:
Änderungen zur Widerrufsbelehrung
Neue Anforderungen an die Informationspflicht von Online-Händlern

In unserem Online-Shop www.lederschlueppchen.de nutzen wir Firegento Germansetup. Werden entsprechende Anpassungen bei Firegento vorgenommen?

Mit freundlichen Grüßen
H. Weinhold

**Comment by Schrank** [comment]
Sehr geehrter Herr Weinhold,

Germansetup wird nicht mehr weiterentwickelt, daher werden die Änderungen hier garantiert nicht übernommen.

Ob das bei dem Nachfolger MageSetup passieren wird kann ich Ihnen aber leider nicht sagen.

Schöne Grüße
Fabian

Von unterwegs gesendet

> Am 05.06.2014 um 20:32 schrieb Holger1975 notifications@github.com:
> 
> Weinhold

**Comment by mklooss** [comment]
dieses Projekt wird nicht weitergeführt.
Aus GermanSetup wurde MageSetup und es werden mehrere Länder unterstützt.

Ein Ticket dazu gibt es dort bereits:
https://github.com/firegento/firegento-magesetup/issues/69

Das Problem generell ist hier wieder, dass es einige Punkte gibt, die von Shop zu Shop unterschiedlich sind.
