### ISSUE TITLE
Keine Agreements im Amazon Payment Checkout

### ISSUE THREAD

**Issue by dusticelli** [firegento/firegento-germansetup#217]
Hallo,

Ich habe das Problem dass ich bei der Zahlart "Checkout by Amazon" die Agreements nicht angezeigt bekomme:

normal sieht das so aus:
http://screencast.com/t/VVVuAWCcZfm

Beim CBA Bestellabschluß dann leider so:
http://screencast.com/t/o7XAjqwj1mAf

Hier kommt es dann auch beim Klick auf "jetzt kaufen" zu einer Fehlermeldung "bitte Bestätigen Sie die Bedingungen" die aber nicht da sind.

Ich habe den Support von der Schnittstelle angefragt und folgende Antwort erhalten:

"our extension includes the standard terms & conditions block provided by Magento. I guess you are using some 3rd party extension (like Firegento) for displaying terms & conditions template, which is removing default block and putting own one instead. It seems that the new block definition doesn't affect Amazon Checkout templates, in such a case please review the documentation of the extension that replaces terms & conditions or contact its vendor to find out how to place missing terms & conditions on pages other standard checkout."

Ich denke man muss irgendwo an die templates oder layout.xml hand anlegen?

Kann mir hier jemand weiterhelfen und sagen was zu ändern wäre, damit im Checkout by Amazon auch die Agreements eingeblendet sind?

**Comment by Schrank** [comment]
Hallo dusticelli, GermanSetup wird zu Gunsten seines Nachfolgers https://github.com/firegento/firegento-magesetup nicht mehr weiterentwickelt.

Installiere bitte MageSetup und probiere es damit.

Unabhängig davon fürchte ich, dass das Plugin für AmazonPayments viele Änderungen macht, die MageSetup nicht erwartet, und daher nicht funktioniert.

Damit das klappt müsste man sich anschauen was das Problem ist. Ich fürchte es wird sich hier niemand finden, der das unentgeltlich tut.

**Comment by dusticelli** [comment]
Hallo Schrank,

danke für die schnelle Antwort. Ich würde ungern jetzt so eine tief in die Logik des Shops eingreifende Extension deswegen ersetzen.

Ist die Installation von magestup evtl. nur wie ein update von firegento? Dann könnte  man es ja probieren, aber wie gesagt ich würde ungern jetzt irgendwelche Steuerparameter usw. erneut anfassen.

Ist es nicht so, dass dieser Block "agreements" irgendwie mit 2 Handgriffen auch dem CBA hinzuzufügen wäre?

**Comment by Schrank** [comment]
Theoretisch sollte es wie ein update sein, ich habe es aber bisher nicht gemacht.

Ansonsten denke ich ja, wenn man was von magento versteht, sollte der block schnell eingefügt sein für amazon payment.
