### ISSUE TITLE
Artikel-Attribut in der price_info.phtml ausgeben (GermanSetup)

### ISSUE THREAD

**Issue by zebulon60** [firegento/firegento-germansetup#218]
Ein froher Gruß in die Runde!

Ich weiß, GermanSetup ist nicht mehr aktuell, aber ein Update zu MageSetup steht derzeit noch nicht zur Debatte (aber das ist ein anderes Thema).

Ich möchte mich dennoch trauen, zur price_infi.phtml eine Frage zu stellen: ich möchte dort die Versandkosten im Klartext aus einem Attribut widergeben (z.B. "zzgl. 17,80 Euro Versandkosten"). Jedoch ergeben meine Versuche entweder eine leere Ausgabe oder den  Fehler "Call to a member function ... on a non-object in...", wenn ich auf die Attribute von $_product zugreifen will.

Ein ähnliches Thema wurde schon mal hier diskutiert:
https://github.com/firegento/firegento-germansetup/issues/68  - "Zugriff auf aktuelles Produkt aus price_info.phtml" - aber leider sind die Vorschläge dort so kryptisch bzw. knapp formuliert, daß ich die entsprechenden Codes wohl noch nicht richtig einbinden konnte.

Jede Hilfe oder Tip wäre hier sehr willkommen!

Cheers,
Johannes

**Comment by Schrank** [comment]
Hallo Johannes, bitte habe Verständnis dafür, dass das ein open source Projekt ist und wir geben uns wirklich Mühe Fehler zu fixen und Probleme zu beseitigen, aber das was du möchtest ist typsche Arbeit für eine Agentur oder Freelancer. Es sind etliche Agenturen und Freelancer an dem Projekt beteiligt die dir sicher gerne gegen entsprechende Entlohnung helfen.

http://www.integer-net.de/
http://www.itabs.de/
http://www.sitewards.com/en/
http://simonsprankel.com/
http://fabian-blechschmidt.de/
http://diglin.ch/

Und viele mehr. (Ihr seid herzliche eingeladen mehr Links zu ergänzen)
