### ISSUE TITLE
Tax-Details

### ISSUE THREAD

**Issue by chris1829** [firegento/firegento-germansetup#219]
Hey guys, 

i have this "problem" since I've opened my online shop. Ive got a good reply for firegento_pdf so i thought i just ask this question here.

In my category view, not the product detail page, i have my product list and under the price are the tax-details with shipping information etc. etc.

![bildschirmfoto 2014-12-03 um 18 09 33](https://cloud.githubusercontent.com/assets/10014364/5284859/9582c4c8-7b17-11e4-9113-ec03ec2f5d67.png)

Can somebody tell me how to remove that? I mean just remove it on the category page, not on the product detail page.

Im working with magento 1.9.

Thanks in advance for the answers

**Comment by Schrank** [comment]
This module is no longer supported. please have a look on [MageSetup](https://github.com/firegento/firegento-magesetup)

**Comment by Schrank** [comment]
You need to remove this from the layout.xml, so copy this xml file to your theme and remove the part or checkout what `addPriceBlockType` and revert it.

https://github.com/firegento/firegento-magesetup/blob/master/src/app/design/frontend/base/default/layout/magesetup.xml#L61-L129

**Comment by chris1829** [comment]
Sorry ich gehe jetzt mal davon aus, dass du Deutsch sprichst, oder?:)
Ich verstehe die Beschreibung gerade nicht so richtig...

**Comment by sprankhub** [comment]
Bitte nur noch hier https://github.com/firegento/firegento-magesetup/issues/116
