### ISSUE TITLE
Firegento - Problem mit einem Template

### ISSUE THREAD

**Issue by GertiNeu** [firegento/firegento-germansetup#220]
Hallo,

ich habe Firegento installiert, leider gibt's Probleme mit unserem (zugekauften) Template.

In der Listenansicht wird beim ersten Aufruf das "zzgl. MwSt." angezeigt.
Es ist ein Ajax-Template, beim Umschalten von Grid zu Liste wird der Block nicht angezeigt.
Ich habe jetzt versucht, das Problem einzukreisen.

Bei der Erstansicht wird die Price.php aus Firegento geladen.
Nach dem Umschalten die code/core/Mage/Catalog/Block/Product/Price.php
Also wird die Price_info.phtml nicht eingebunden.

Hat jemand eine Idee, wie ich das Problem lösen könnte?

**Comment by Schrank** [comment]
xdebug ist dein Freund. Was anderes als wühlen und schauen was passiert können wir auch nicht, machen wir aber gerne - gegen Geld. Wenn du Hilfe möchtest, schau einfach mal nach, wer alles an dem Projekt gearbeitet hat und frage sie.

germansetup wird zugunsten von MageSetup nicht mehr weiterentwickelt, möglicherweise verschwindet dein Problem auch einfach, wenn du MageSetup installierst.

Viel Erfolg!
