### ISSUE TITLE
Modulaufruf GermanSetup beim Start

### ISSUE THREAD

**Issue by stemalo** [firegento/firegento-germansetup#221]
Bei mir liegt alles brach. Habe nur das Modul GermanSetup im Backend deaktiviert und als Ergebnis ist das meine Seite nicht mehr erreichbar ist und auch das Backend. 

a:4:{i:0;s:78:"Module "IntegerNet_GermanStoreConfig" requires module "FireGento_GermanSetup".";i:1;s:723:"#0 /home/www/garte/htdocs/app/code/core/Mage/Core/Model/Config.php(849): Mage::throwException('Module "Integer...')

Wie schalte ich den Modulaufruf beim Start ab ?

**Comment by Schrank** [comment]
Hi stemalo,

die Fehlermeldung sagt, dass du das Modul IntegerNet_GermanStoreConfig auch abstellen musst, denn es erwartet GermanSetup.

Was genau hast du den vor?

**Comment by stemalo** [comment]
Danke für die mehr als schnelle Antwort. Ich habe das Modul im Backend deaktiviert weil ich das Nachfolgemodul MageSetup installiert habe. Und nun komme ich nicht mehr ins Backend. Ich weiss nur nicht wo ich das Modul abstelle. In der XML-Datei ? Ich versuche das mal.

**Comment by Schrank** [comment]
jep in der modul XML datei. wahlweise kannst du einfach https://github.com/integer-net/GermanStoreConfig/blob/master/src/app/etc/modules/IntegerNet_GermanStoreConfig.xml ändern und aus dem GermanSetup ein MageSetup machen. Wenn in dem Modul allerdings irgendwo GermanSetup Klassen benutzt werden, müsste man das auch noch fixen.

**Comment by stemalo** [comment]
Hallo Fabian, 
vielen Dank für deine schnelle und vor allem wirksame Hilfe. Letztlich hast Du mich auf die richtige Spur gebracht. Danke dafür. 
Gruss
Peter
