### ISSUE TITLE
change default value for meta_autogenerate ?

### ISSUE THREAD

**Issue by thomasklosinsky** [firegento/firegento-germansetup#223]
Hi there,
how can I change meta_autogenerate default value in Magento V1.7.0.2 and German Setup 1.2.3?

**Comment by Schrank** [comment]
Hi Thomas,

I think there is no easy way, but I might be wrong. You need to change the default value in the database either by writing a script or by directly editing the database.

German setup is no longer supported, but you might get an answer here: https://github.com/firegento/firegento-magesetup/issues
