### ISSUE TITLE
Attributes not shown with sidebar cart

### ISSUE THREAD

**Issue by vovayatsyuk** [firegento/firegento-germansetup#226]
This issue was fixed in `firegento-magesetup` on 17 Feb 2014

Please merge it into this repository too:

https://github.com/firegento/firegento-magesetup/commit/d9c9044c3331f396362c88fac68dc7a6634f359b#diff-3e62a979f18abea74a89c6077446dec5

**Comment by sprankhub** [comment]
No, this extension is not maintained any more. Please update to MageSetup.
