### ISSUE TITLE
Newsletter Historie

### ISSUE THREAD

**Issue by Marx15** [firegento/firegento-germansetup#227]
Hallo Support-Team

ich habe eine Frage zur Funktion "Newsletter-An- und -Abmeldungen Historie"
Diese hatte noch vor kurze funktioniert. Jetzt lande ich plötzlich auf eine 404 Seite.
Benutze seit immer Magento Version 1.9.0.1.

Habt Ihr vielleicht eine Idee?

Danke schonmal

**Comment by Schrank** [comment]
Hi Marx,

Diese Modul wird nicht mehr supportet.

Wir empfehlen MageSetup zu installieren. Wenn sich damit das Problem nicht löst, mach gerne im anderen Repo ein Issue auf!
