### ISSUE TITLE
Migration and Upgrade

### ISSUE THREAD

**Issue by michaelhettwer** [firegento/firegento-germansetup#228]
Hi,

i am using the germansetup module. I want to migrate my data to magento2. 
My Shop is up-to-date (magento 1.9.3.2) but actually i am running the "old" germansetup.
In the readme there is a hint, i only had to replace the extension germansetuop with magesetup.
Is this really possible? Should i use the magento downloader or should i copy the files manually? 
After that i would like to migrate. I will use the new magesetup magento2 extension.

michael

**Comment by Schrank** [comment]
Exchanging germansetup with magesetup isn't needed.

M2 is totally different from M1, so there is no easy migration path. Don't spend your time on the migration from german to magesetup, but instead learn M2, install magesetup and reconfigure it as needed - my 2 cents.

**Comment by michaelhettwer** [comment]
Reconfigure will be much easy. Thanks a lot. I m just running down the migration list, did not mentioned only to install it new ;-)
