### ISSUE TITLE
PDF Rechnung

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-germansetup#23]
Hallo,

die PDF-Rechnung ist, wenn ich da so richtig sehe, noch nicht wirklich einsetzbar im deutschen Markt.
Wird das auch Bestandteil der Extension? Gibt es bereits Ansätze?

/Maxi

**Comment by mklooss** [comment]
du kannst dir auf die Schnelle die Extension dann aus dem MRG Paket raus ziehen, sprich die PDF Veränderungen...

**Comment by easyMaxi** [comment]
Ja, auf die Schnelle hilft mir das vielleicht schon.
Meine Frage war mehr auf die Zukunft der Extension gerichtet.
Ob eine Schemarechnung usw. angedacht ist. Und wenn nein ist es hiermit vorgeschlagen :D

**Comment by therouv** [comment]
Hi easyMaxi,

prinzipiell wollen wir die GermanSetup-Extension so schlank wie möglich halten und nicht mit so mit Extensions vollpacken wie es MRG macht. Ich hab dein Issue aber mal als "FEATURE" gelabeled.

Ich persönlich kann mir aber gut vorstellen, dass man evtl. ein eigenes PDF-Modul via Firegento entwickelt und das ebenfalls mit anbietet.

Viele Grüße,
Rouven

**Comment by therouv** [comment]
Wird nun definitiv in einem eigenen Modul entwickelt. Fortschritte können hier verfolgt werden: https://github.com/firegento/firegento-pdf
