### ISSUE TITLE
Kompatibilität zu Modul "Sitewards Extensionb2b Professional"

### ISSUE THREAD

**Issue by therouv** [firegento/firegento-germansetup#24]
GermanSetup + Sitewards Extensionb2b Professional (https://www.magentocommerce.com/magento-connect/Sitewards/extension/4864/sitewards_b2bprofessional ) funktionieren out-of-the-box nicht zusammen, da beide die gleichen Klassen überschreiben. 

Evtl. findet sich hier ja ein Lösungsansatz um die Kompatibilität zu gewährleisten?

**Comment by tobi-pb** [comment]
Ui, cool. Ich gucke mal!

**Comment by tobi-pb** [comment]
Wenn wir das lösen sollte das ja etwas generischer sein. Was haltet ihr davon wenn wir bei Änderungen im Warenkorb die Taxrate in die Session schreiben und parallel dann im Config-XML den Wert für tax/classes/shipping_tax_class manuell überschreiben? 

Dann können wir uns doch den Rewrite komplett sparen..

**Comment by therouv** [comment]
Nun, die Tax Config wird in dem Sitewards-Modul nicht überschrieben. In dem Sitewards Modul werden die Klassen überschrieben, die wir dynamisch via Price Renderer neu setzen. Dadurch kann die Sitewards-Logik nicht mehr ausgeführt werden.

Beispiel: Klasse Mage_Catalog_Block_Product_Price

Zu deiner Idee:
Könnten wir mal testen - müssen nur einmal schauen, wie es sich mit dem Caching verhält. Ich vermute fast, dass wir so jedes Mal den Config-Cache löschen müssen damit der neue Wert gezogen wird.

**Comment by tobi-pb** [comment]
Sorry, das ist mir jetzt aber peinlich. Ker ker ker :( Ich gucke mir das noch mal an - diesmal nüchtern ;)

**Comment by grossmann** [comment]
Hallo, gibt es dazu schon eine Lösung? Ich brauche die Funktion von Sitewards B2b um die Preise für Gäste auszublenden. Vielleicht gibts es auch einen schnellen work around? Oder wo könnte ich da selber ansetzen (bin allerdings kein großer Coder)?
Danke für die Hilfe!
