### ISSUE TITLE
Unterstützung von weiteren Ländern beim Setup

### ISSUE THREAD

**Issue by therouv** [firegento/firegento-germansetup#25]
Das Modul sollte dahingehend umgeändert werden, dass man prinzipiell auch Konfigurationen für andere Länder mitliefern kann. Bei der Installation sollte man dann ein Land auswählen können, für welches das Setup ausgeführt werden soll.

**Comment by drlrdsen** [comment]
Das würde ich nicht machen. Das ist doch eine Anforderung, die in einem Bruchteil der Anwendungsfälle überhaupt relevant ist. Ich würde die Geschichte einfach halten und das wäre einfach ein Modul für Deutschland und nicht mehr.

Viele Grüße
Michael

Von meinem iPad gesendet

Am 22.05.2012 um 13:59 schrieb "Rouven Alexander Rieker" reply@reply.github.com:

**Comment by therouv** [comment]
Ich meinte nicht zusätzlich zu der deutschen Konfiguration, sondern stattdessen.. Sprich: ein schweizer Shop-Betreiber kann sich den Shop für die Schweiz konfigurieren und nicht Schweiz + Deutschland.

**Comment by drlrdsen** [comment]
Besser. ;)

Von meinem iPad gesendet

Am 22.05.2012 um 14:19 schrieb "Rouven Alexander Rieker" reply@reply.github.com:

**Comment by avstudnitz** [comment]
Funktionalität umgesetzt und im Master. Das Modul unterstützt jetzt für die zusätzlichen XML-Dateien eine neue Ordnerstrutur. 
-- default
---- tax.xml
---- cms.xml
---- email.xml
-- at
---- tax.xml
-- ch
---- tax.xml

Steuereinstellungen für Österreich und Schweiz sind integriert.
