### ISSUE TITLE
modman: ERROR: firegento-germansetup does not contain a "modman" module description file.

### ISSUE THREAD

**Issue by tobi-pb** [firegento/firegento-germansetup#26]
Ich hätte total gerne das Projekt einfach per modman clone gezogen und daran gearbeitet.  Leider bekomme ich einen Fehler:

modman clone firegento-germansetup https://github.com/firegento/firegento-germansetup/
ERROR: firegento-germansetup does not contain a "modman" module description file.
Error trying to clone new module 'firegento-germansetup', operation cancelled.

Wie macht ihr es das es automatisch geht? Liegt die Datei einfach falsch?

**Comment by drlrdsen** [comment]
Ich kenne mich mit Modman nicht aus, aber: Es gibt noch ein Unterverzeichnis src innerhalb des Moduls, in welchem die Datei liegt. Ich schätze, deswegen kannst du darauf nicht einfach so zugreifen.

**Comment by tobi-pb** [comment]
Also kann ich die Datei verschieben + anpassen? Im Root klappt es nämlich einwandfrei :)

**Comment by gerritpechmann** [comment]
Ich binde in Projekten die Extension in meinen .modman Ordner per svn:external ein, wobei ich da direkt auf das src Unterverzeichnis durchgreife:

FireGento_GermanSetup https://github.com/firegento/firegento-germansetup.git/trunk/src

Wenn wir die modman Datei in das Root-Verzeichnis legen, dann hätten wir das src Verzeichnis mit im modman Paket, was nicht so schön wäre.

**Comment by gerritpechmann** [comment]
Meiner Meinung spricht nichts dagegen, das Verzeichnis umzustellen, wie bei diesem Fork https://github.com/ffuenf/firegento-germansetup

**Comment by drlrdsen** [comment]
Ich bin gegen die Umstellung des Verzeichnisses. Normalerweise gehört auf Top-Level ja noch ein Verzeichnis build, wo die verschiedenen releasten Versionen des Moduls hinterlegt werden sollten, so dass diese erhalten bleiben.

**Comment by tobi-pb** [comment]
Git kann keine Checkout aus Subdirs deswegen muss die Datei eigentlich ins Root. Sonst kann man es nicht korrekt mit Modman nutzen :( Oder hat jemand eine Idee?

**Comment by gerritpechmann** [comment]
Damit man das Modul vernünftig mit git submodules und modman nutzen kann, bin ich dafür das Verzeichnis umzustellen. Wir bräuchten auf dem Top-Level kein Verzeichnis "build", wenn wir die Pakete taggen und (wie jetzt ja auch schon) als Download einstellen. 

@drlrdsen Ich seh' momentan den Vorteil der "src" und "build" Verzeichnisse nicht.

**Comment by therouv** [comment]
Ich denke ein Kompromiss wäre, wenn man die modman-Datei entsprechend ins Root-Verzeichnis verschiebt und darin die Pfade entsprechend anpasst.

Ansonsten bin ich einer Meinung mit @gerritpechmann - Wir taggen ja die Releases und benötigen aus diesem Grund eig. keinen "build" Ordner.
