### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#28]
wäre es nicht Sinnvoll wie Tags anzulegen, für die Versionen die im Connect gelandet sind?

So wie es auch das Sprachpaket macht:
https://github.com/dsdata/German_LocalePack_de_DE/tags

**Comment by millejano** [comment]
Tags sind auf jeden Fall sinnvoll.

**Comment by drlrdsen** [comment]
Dito.

**Comment by mklooss** [comment]
git tag -a v1.0
git push --tags

**Comment by therouv** [comment]
Finde ich gut. Da der master branch ja mittlerweile schon weiterentwickelt wurde, würde ich vorschlagen, dass wir das ab dem nächsten Release konstant durchführen.

**Comment by drlrdsen** [comment]
du kannst Tags an beliebige Commits anhängen. Wissen wir denn noch welche Version online gegangen ist. Dann kann man das Tag auch nachträglich noch bringen.

**Comment by drlrdsen** [comment]
Ups, sorry. Falscher Knopf ;)

**Comment by millejano** [comment]
Sinnvoll wäre sicherlich auch eine 2. branch testing oder dev in der entwickelt wird anzulegen und der master wäre immer die letzte stable version. Zum Tagging, da sollte einer der Hauptbeteiligungen mal nachtaggen am besten mit 3-4 Stellen also 1.0.0.1 usw. 

Wenn da Hilfe benötigt wird da einfach fragen oder https://github.com/dsdata/German_LocalePack_de_DE/issues/24 befolgen.

Grüße, millejano

**Comment by therouv** [comment]
Ich hab da mal was vorbereitet: https://github.com/firegento/firegento-germansetup/tags

Version 1.0.0 ist nun mit dem aktuellen Stand aus MC getagged. Müssen das halt bei den zukünftigen Releases entsprechend berücksichtigen und mitmachen. 

Habe den Tag entsprechend der Modul-Version benannt und keine 4. Stelle oder so eingefügt.
