### ISSUE TITLE
falsche Steuerregeln nach 1. Setup

### ISSUE THREAD

**Issue by millejano** [firegento/firegento-germansetup#29]
Nach dem 1. Setup, bei dem auch der Punkt 'Umsatzsteuerpflichtige Güter 7%' noch nicht zur Verfügung steht, gibt es einige Abweichungen von einem sinnvollen Setup z.B. 'Versand mit 19% Mwst.' ist der Steuersatz 7% zugewiesen.

Mehr siehe Screenshot:  http://250kb.de/u/120611/p/B9xA3mDT5uMr.png

Grüße, millejano

**Comment by millejano** [comment]
Ein Versuch die Einstellungen für die Kundensteuerklasse Unternehmen z.B. bei 'Produkte mit 7% MwSt.' zu Ändern führt zur Fehlermeldung Code existiert bereits.

Grüße, millejano

**Comment by mklooss** [comment]
hast du mal versucht die Steuerklassen zu löschen?

**Comment by mklooss** [comment]
problem solved?

**Comment by therouv** [comment]
Ich schließe das mal. Kann bei Bedarf dann wieder geöffnet werden.

**Comment by luckyduck** [comment]
Das kann ich zumindest bei 1.7.0.2  bestätigen. Problem ist, dass der Name "Produkte mit 19% MwSt." zweimal für Steuerregeln verwendet wird: sowohl für Kundensteuerklasse "Endkunden" als auch für Kundensteuerklasse "Unternehmen". Beim Import funktioniert dies, da kein Unique Index auf der Spalte liegt. Magento verhindert über das Model jedoch doppelte Namen. Wenn eine von beiden einen abweichenden Namen erhält, funktioniert es einwandfrei. Z.B.:
- Produkte mit 19% MwSt. (Endkunden)
- Produkte mit 19% MwSt. (Unternehmen)

**Comment by tobi-pb** [comment]
Scheint noch nicht gelöst zu sein, siehe Kommentar von Jan

**Comment by avstudnitz** [comment]
Ein Problem habe ich im Dev-Branch gelöst - Versandsteuerregel und die Regel für reduzierte MwSt. waren verstauscht. Das ist das Problem aus dem Screenshot im Ursprungsposting.

**Comment by riconeitzel** [comment]
Ich schaue mal, wie das mit Mehrfacheinträgen in der Datenbank beim Import ge'handled wird. Ich hatte das o.g. Problem auch schonmal.

**Comment by riconeitzel** [comment]
Okay, ja, das Problem besteht noch. Ich habe aktuell nen PullRequest #111 offen, da werde ich nochmal draufschauen …

**Comment by riconeitzel** [comment]
Okay, ist mit #111 erledigt. Wenn der PullRequest ge'merged ist, kann das hier geschlossen werden.
