### ISSUE TITLE
Button Lösung - Checkout Seite

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#30]
Ich mach das Thema hier mal auf ;-)

Wenn man sich viele Informationen anschaut, muss man ja den Checkout von Magento umbauen, damit er konform ist.

> http://www.it-recht-kanzlei.de/buttonl%C3%B6sung-informationspflichten.html
> 
> http://www.shopbetreiber-blog.de/2012/06/12/kostenloses-whitepaper-bestellseite-button-loesung/

**Comment by avstudnitz** [comment]
Ist seit https://github.com/firegento/firegento-germansetup/pull/20 bereits integriert.

**Comment by mklooss** [comment]
Naja es ist ja nicht nur der Button an sich, sondern auch der Aufbau der Review Seite.

daher ist das Thema eigtl. so noch nicht geschlossen, in meinen Augen.

**Comment by avstudnitz** [comment]
Unserer Meinung nach deckt der normale Checkout mit unseren Änderungen die Anforderungen ab. Was fehlt denn deiner Meinung nach?

**Comment by mklooss** [comment]
Wenn ich das in den Beiden Links oben lese, so darf zwischen dem Kaufen Button und den Inhalt der Bestellung nicht mehr stehen, dazu gehören auch die AGB / Widerrufsrecht (welche ja per Default dazwischen sind), die wurde darüber gelegt.

Dann sollte die Anzahl der Artikel sowie der Preis der einzelnen Positionen hervorgehoben werden.

**Comment by avstudnitz** [comment]
Hier noch eine Anfrage zu dem Thema, die ich per Email bekommen habe:

Sehr geehrter Herr v. Studnitz

Wir hatten das schon installiert und finden Ihr Paket eigentlich ganz sympathisch. Den Extensionwerbeterror von symetrics und die Tatsache, dass die immer ein halbes Jahr später kommen, veranlasst uns, das nicht mehr zu installieren.

Was die Button-Lösung anbetrifft, habe ich bei Ihrer Lösung Bedenken. 

http://www.shopbetreiber-blog.de/wp-content/uploads/2012/06/120612_Muster-Bestellseite.pdf

Das ist der Vorschlag von trusted shops, der nicht nur rechtlich, sondern auch für die Zertifizierung relevant sein dürfte.

http://www.shopbetreiber-blog.de/2012/06/04/button-loesung-bestellseite/
Das ist die Beschreibung dazu mit Anwaltskommentar.

Es gibt sicher viele Varianten der Buttonlösung, und es wird dauern, bis die Rechsprechung das alles geklärt hat. 

Ich denke nur, dass die Buttonbeschriftung bei Ihrer Lösung nicht ausreicht (leicht korrigierbar), aber auch die Position der AGB und der Widerrufsbelehrung, die oben drüber sein sollte. So stehts im Gesetz. Bei Ihnen ist die drunter. 

Wie sehen Sie das?

Mit freundlichen Grüßen
Karl Gunkel

Gunkel Consulting

**Comment by therouv** [comment]
Ich habe gerade noch folgenden Artikel gelesen: http://www.seo-diaries.de/2012/06/neuer-bestellvorgang-bei-online-shops-fluch-oder-segen/ Dort haben Sie folgendes Bild veröffentlicht: http://www.seo-diaries.de/wp-content/uploads/Bildschirmfoto-2012-06-19-um-20.28.45.png

Ich denke, dass die Rechnungsanschrift + Lieferanschrift + Zahlungsart ja schon entsprechend durch die Spalte rechts/links im OnepageCheckout abgedeckt ist. Der Button wurde auch schon entsprechend im deutschen Sprachpaket umbenannt.

Fehlt also nur noch die AGB + Widerrufsbelehrung über die Artikel zu positionieren + die Artikeldarstellung anzupassen. 

Bei der Produktbeschreibung würde ich aber höchstens nur die Short-Description anzeigen lassen. Wesentliche Merkmale müsste dann ein Shop-Betreiber individuell anpassen, da das ja von Produkt zu Produkt unterschiedlich sein kann.

**Comment by avstudnitz** [comment]
Die Short Description kann je nach Shop ganz schön umfangreich sein - ich würde das konfigurierbar machen, ob man sie anzeigen lassen will oder nicht.
AGB + Widerrufsbelehrung über die Artikel? Geht auch unter den Button?

**Comment by therouv** [comment]
Unter dem Button wird Trusted Shops + Gesetzgeber vermutlich nicht akzeptieren, da diese ganze Aktionen VOR dem Kaufen Button getätigt werden müssen.

**Comment by mklooss** [comment]
Der erste Step war "der einfache" erstmal die Bestellbedingungen vor die Produkte zu bringen.

https://www.gunah.eu/images/germansetup/button.png
und ein paar Design Änderungen, hier habe ich erstmal nur die Preise Fett gemacht.

Konfigurierbare Produkt Option, sowie Individuelle Optionen, werden ja von Haus aus angezeigt.
Jetzt sollte wenn ein Attribute hinzugefügt werden, welche für "Spezielle" Preisinformationen enthält.

Die Frage hier nur, wie fügt man diese am besten den Quote's hinzu?

**Comment by therouv** [comment]
> Konfigurierbare Produkt Option, sowie Individuelle Optionen, werden ja von Haus aus angezeigt.
> Jetzt sollte wenn ein Attribute hinzugefügt werden, welche für "Spezielle" Preisinformationen enthält.

Die Frage muss lauten: Was sind spezielle Preisinformationen und sind sie in jedem Shop gleich? Falls sie in jedem Shop unterschiedlich sind (wovon ich derzeit ausgehe), dann müssen wir das meines Erachtens nach nicht in GermanSetup berücksichtigen. 

Prinzipiell fände ich eine Art Auswahlmöglichkeit im Backend nett (wie @avstudnitz es schon vorschlug), wo man alle Attribute auflistet und der Shop-Betreiber dann wählen kann, welche er im Checkout angezeigt haben möchte.

**Comment by riconeitzel** [comment]
Kann man nicht das EAV Modell erweitern und den Attributen eine zusatzkonfig anhängen wie visible_on_checkout - und das mit magento mal klären? Das Problem ist ja in Deutschland immanent.

**Comment by avstudnitz** [comment]
Naja, eine einfache Multiselect-Liste in der Konfiguration würde es wahrscheinlich auch tun, oder? Oder, wenn die Reihenfolge benötigt wird, so ein Konfigurations-Element, bei dem man Zeilen hinzufügen kann. In jeder Zeile könnte man dann ein Attribut auswählen und eine Reihenfolge festlegen.

**Comment by riconeitzel** [comment]
Das ja, wird aber bei vielen Attributen schnell unübersichtlich - und im Grunde wäre es am EAV auch sinnvoller aufgehoben, oder?

**Comment by riconeitzel** [comment]
Außerdem glaube ich fast, dass es dort schneller zu realisieren wäre.

**Comment by therouv** [comment]
@mklooss Magst du den ersten Commit mit dem AGB über Artikel verschieben schon einmal als Pull-Request im "development" Branch öffnen? Dann könnte ich das da schon mal mergen.

**Comment by mklooss** [comment]
Ich habe mal eine kleine Erweiterung gemacht, die mir die Basics schon mal abnimmt.
https://github.com/mklooss/Loewenstark_Button

Ähnlich zu den Änderungen die ich commited habe

**Comment by tobi-pb** [comment]
Ich habe jetzt auch einige Artikel dazu gelesen und ich vermute wir können erst eine wirklich Lösung finden wenn ein paar Richter geurteilt haben was wirklich sein muss, und was kann. 

Welchen Unterschied es machen soll ob die AGB über der Artikelliste steht oder darunter ist mir z.B. ein Rätsel. Wichtig ist doch letztlich nur das der Bestellen-Button drunter ist.. aber wie gesagt: Wir müssen wohl etwas warten ..

**Comment by therouv** [comment]
Ich hab mir gerade einmal angeschaut, wie das in der neuesten Version von MRG gelöst wird: http://cl.ly/image/3c0A2E3Z3u3x

Fazit daraus:
- _Prinzipiell haben wir mit der Änderung von @mklooss im Pull Request #32 schon einen Teil abgehakt_ **=> Erledigt**
- _Der Text "zusätzlich fallen noch Kosten oder Steuern an, die nicht über uns abgeführt bzw. von uns in Rechnung gestellt werden" kommt aus einem Feld in der Systemkonfiguration und kann frei definiert werden._ **=> Erledigt**
- _Der Button benennt MRG in "zahlungspflichtig bestellen" um => meiner Ansicht nach ist das ein Fall für @riconeitzel und das Sprachpaket. Der Gesetzgeber lässt ja auch "Jetzt kaufen" zu._ **=> Sprachpaket**
- _Der Text "Short Description" kommt aus dem entsprechenden Attribut, welches man im Backend in der Systemkonfiguration individuell definieren kann. Hier fände ich persönlich aber eine Mehrfachauswahl schicker._ **=> Erledigt**

**Comment by riconeitzel** [comment]
Die Buttondiskussion sollten wir ggf. https://github.com/dsdata/German_LocalePack_de_DE/issues?sort=created&state=open hier führen. Ich denke aber, dass "jetzt kaufen" auch wenig Angriffsfläche bietet, da das Wort "kaufen" einen verbindlichen Vertragsabschluss mit beiderseitigen Verpflichtungen impliziert.

**Comment by therouv** [comment]
Hier noch eine interessante Case-Study zur Benennung des Buttons: http://www.explido.de/buttonloesung/

**Comment by mklooss** [comment]
https://github.com/mklooss/Loewenstark_Button
Ich habe heute mal einen weiteren Schritt veröffentlicht, hier wurde die Idee die von Rico genannt wurde umgesetzt.
Es kann im EAV Catalog Attribute die Option "is_visible_on_checkout" gesetzt werden.

An der Stelle habe ich dann die Standard Attribute Liste von Magento verwendet, und erweitert (Custom Option / Configureable Products).

Bezieht sich alles aber nur auf den Onepage Checkout :)

**Comment by therouv** [comment]
So, mit dem jetzigen Push sollten die meisten Punkte zur Button-Lösung abgehakt sein. Wäre klasse, wenn sich das jemand von euch anschauen könnte und einmal durchtesten könnte. Dann könnten wir auch das neue Release für MagentoConnect veröffentlichen.

**Comment by heidelberg** [comment]
Habe den Loewenstark_Button auf Magento 1.5.1.0 überspielt und es funktioniert sehr gut. Bei den Attributen wird allerdings nur das Attribut sku im Warenkorb und im Onepage Checkout angezeigt, obwohl ich auch bei anderen Attributen (z.B. short_description) die Option "is_visible_on_checkout" gesetzt habe.

**Comment by mklooss** [comment]
@heidelberg ist der Fehler auch unter FireGento GermanSetup?
sonst einfach in dem Repo ein Issue verfassen...

**Comment by heidelberg** [comment]
Ich habe nochmals FireGento GermanSetup und den Loewenstark_Button auf Magento 1.5.1.0 aufgespielt. Diesmal funktioniert alles wunderbar, auch werden die ausgewählten Attribute angezeigt. 
Vielen Dank für diese tolle Arbeit.

**Comment by mklooss** [comment]
habe mal bei mir die Option hinzugefügt, dass man Agreements nicht bestätigen muss:

> https://github.com/mklooss/Loewenstark_Button/commit/529a82a57d94dcb7d62b11e2e3631a470c10b677

Da mit der Button Lösung ja die Agreements nicht mehr bestätigt werden müssen. (siehe Leitfaden Trusted Shops).

**Comment by mklooss** [comment]
wenn ich das jetzt mehrfach gelesen habe, muss im Checkout Review auch das Artikelbild auftauchen

**Comment by mklooss** [comment]
Ich denke dieser Issue kann soweit zu, dann sollten neue aufgemacht werden, wo die Probleme genau definiert werden... einfach zur Übersicht
