### ISSUE TITLE
Fehler in Email Templates

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-germansetup#31]
In fast allen Email-Templates gibt es einen Fehler bei der Einbindung des Logo-Bildes:

```
<a href="{{store url=""}}"><img src="{{skin url="images/logo_email.gif" _area=''frontend''}}" alt="{{block type="germansetup/imprint_field" value="shop_name"}}" style="margin-bottom:10px;" border="0"/></a>
```

Die _area ist mit zwei einfachen Anführungszeichen (' und ') anstatt einem Einfachen oder Doppelten (' oder ") eingeschlossen. Dadurch wird das Bild im adminhtml und nicht im frontend gesucht und nicht gefunden.
So sollte das richtig sein:

```
<img src="{{skin url="images/logo_email.gif" _area='frontend'}}" ... }}"... />
```

**Comment by mklooss** [comment]
es muss meiner Meinung nach mit Doppelten Anführungszeichen sein

```
<img src="{{skin url="images/logo_email.gif" _area="frontend"}}" ... }}"... />
```

**Comment by avstudnitz** [comment]
Angepasst im Sprachpaket.
