### ISSUE TITLE
Produktsteuerklassen Schweiz

### ISSUE THREAD

**Issue by nickweisser** [firegento/firegento-germansetup#34]
Wenn man bei der Initialisierung "Versand aus Schweiz" auswählt, bleiben unten unter "Produktsteuerklassen neu zuweisen" in den Dropdowns "Umsatzsteuerpflichtige  Güter 19%" stehen: http://screencast.com/t/zByiwibAudM

Wenn man die Initialisierung durchführt, werden dann zwar die korrekten Steuersätze angewendet, aber es wäre dennoch hilfreich, wenn man entweder eine Zusatzinfo anbringt oder die Steuersätze korrekt anzeigt, wenn das Land gewechselt wird. Letzteres ist mir zu anspruchsvoll, um es programmiertechnisch umsetzen zu können, ersteres könnte ich selbst als Pull Request beisteuern.

Was meint ihr dazu?

**Comment by mklooss** [comment]
Es ist an sich nur ein Wording Problem, da es nur der Name der "Tax Class" ist.

**Comment by avstudnitz** [comment]
Ich bin dafür, die Produktsteuerklassen korrekt anzuzeigen. Ich kann mir das nächste Woche ansehen, wenn das bis dahin niemand anders erledigt hat.

**Comment by nickweisser** [comment]
OK, in dem Fall würde es vermutlich reichen, wenn man die Steuerklasse 
so umbenennt, dass diese für alle 3 Ländern Sinn ergibt?

**Comment by therouv** [comment]
Eine relativ allgemeingültige Lösung wäre:
- Regulärer Steuersatz
- Reduzierter/Ermäßigter Steuersatz
- Versandsteuersatz

Was meint ihr?

**Comment by avstudnitz** [comment]
Ja, ist gut. Können wir gern so machen.
