### ISSUE TITLE
CMS-Blöcke werden nicht an Transaktions-Emails angehängt (Magento 1.7)

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#36]
Kommentar unter http://www.avs-webentwicklung.de/nc/blog/artikel/magento-german-setup-die-alternative-zu-market-ready-germany-ua.html:

..erstmal ein Dankeschön, dass so eine Extension der Community kostenlos zur Verfügung gestellt wird.
In meiner 1.7 Magento Installation funktioniert die Extension eigentlich wie gewünscht, jedoch wird bei den Transaktionsemails weder die beiden Blocke angehangen (gs_revocation, gs_business_terms) noch das Impressum ({{block type="germansetup/imprint_content" template="germansetup/imprint/email_footer.phtml"}})
..eine Idee woran das liegen könnte? 

Sowie 

Bei 1.7 das gleiche Problem, gibts da eine Lösung?

**Comment by jwohlfeil** [comment]
Es wird folgende Warnung ausgegeben, vielleicht hilft das:

Warning: include(Mage.php) [function.include]: failed to open stream: No such file or directory in /Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/lib/Varien/Autoload.php on line 93

Warning: include() [function.include]: Failed opening 'Mage.php' for inclusion (include_path='/Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/app/code/local:/Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/app/code/community:/Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/app/code/core:/Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/lib:.:/Applications/MAMP/bin/php/php5.3.6/lib/php') in /Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/lib/Varien/Autoload.php on line 93

Fatal error: Class 'Mage' not found in /Volumes/Daten/Users/jw/Sites/webroot/notizblock-de/app/code/core/Mage/Core/functions.php on line 244

**Comment by jwohlfeil** [comment]
Weiterer Hinweis: Das Problem kommt wohl aus FireGento_GermanSetup_Block_Imprint_Content, sobald der Block irgendwo in den Mail Templates eingebunden wird, gibt es den o.g. Fehler. Nur das Template germansetup/imprint/email_footer.phtml anzupassen reicht nicht aus, der Fehler erscheint trotzdem.

**Comment by avstudnitz** [comment]
Problem mit Umstellung auf Sprachpaket-Emails behoben.
