### ISSUE TITLE
Rechnungs Anzeige in Verbindung mit Advanced Invoice

### ISSUE THREAD

**Issue by OrinocoDelta** [firegento/firegento-germansetup#38]
Hallo zwei Sachen: 

1) wie sieht es mit der Button Lösung aus - schon ein Update in Vorbereitung??? 

2) Wir nutzen AdvancedInvoice von vianetz..... dort lässt sich einstellen, das der Name des Steuersatzes in den PDF Rechnungen angezeigt werden kann! 

Dieses wird aber nicht gemacht, in den Rechnungen wird lediglich MwSt. angezeigt! Wir würden aber gerne noch 19% davor haben... Die Steuerkennung der Extension wird ja nicht genommen ;-(((

(Steuer-Name wird aus Verkäufe / Steuern / Steuerzonen und -sätze verwendet) 

Ein Feedback bzw. Hilfe wäre nett, nen ganzen Tag alles mögliche probiert - aber kein Erfolg ;-(((

**Comment by therouv** [comment]
Hallo,

zu 1) siehe Issue #30

zu 2) Bei bereits existierenden Bestellungen im Shop lässt sich das nachträglich nicht mehr so einfach ändern. Prinzipiell kannst du den Namen des Steuersatzes aber immer wie hier angeben: http://cl.ly/image/1J281l1C2c19 - Wir könnten das zwar beim Setup mit einfügen, haben es aber vermutlich aus dem Grund rausgelassen, dass ein Shop mehrere StoreViews haben kann und wie der Steuerbezeichner in dem jeweiligen Store lauten muss (19% MwSt., VAT 19%, ....)

Grüße

**Comment by OrinocoDelta** [comment]
Hallo Rouven Alexander ;-)

Super! Danke erstmal für das schnelle Feedback - nun das mit der Steueranzeige in AdvancedInvoice PDF-Email Rechnung ist halt ein wenig tricky…. ich versuche mal Deinen Ansatz und werde berichten wie ich es dann am Ende gelöst habe… Das Thema ist, dass ich mir die ganze gedacht habe, dass:

Steuerkennung, Land & Satz zusammengesetzt werden ;-) In Verbindung mit GOMAGE Onepage Checkout funktioniert mit der Initial Lösung von Euch alles wunderbar im Backend - aber dann nicht mehr in den PDF Rechnungen… Werde jetzt mal sehen was ich da machen kann…

Eventuell noch eine eine Verständnis Frage:

https://github.com/firegento/firegento-germansetup/commit/ebcb5179575d731c536c50ce603c302f320757d0

Funktioniert das ganze auch für Custom Theme's ??? Oder ist dieser Part sowieso nicht mehr aktuell, weil Ihr jetzt in dieser Richtung (https://github.com/mklooss/Loewenstark_Button) entwickelt?

Bis zum nächsten mal,

Grüsse OrinocoDelta

**Comment by therouv** [comment]
Ich sag mal so: Wenn der originale Onepage Checkout von Magento genutzt wird, sollte das _rein theoretisch_ schon klappen, es sei denn dort wurden schon Änderungen vorgenommen.

Firegento bekommt auch eine Implementierung der Button-Lösung. Inwieweit die sich von dem genannten Modul entscheidet wird sich zeigen.

**Comment by OrinocoDelta** [comment]
Onepage Checkout von Magento ist aktiv und wurde nicht verändert! Einzig die Extension OnePage Checkout von GOMAGE wird genutzt… (siehe: http://developer.olis-teile-shop.de/ersatz-und-reparaturteile) … ich denke mal wenn ich es jetzt nicht falsch verstanden habe, dann wird die Reihenfolge im checkout auch hier funktionieren müssen… oder?

**Comment by therouv** [comment]
Ich habe diese Extension noch nie eingesetzt, deshalb kann ich es leider nicht damit prüfen. _Rein theoretisch_ könnte das schon klappen - müsste man einfach mal testen :-)

**Comment by OrinocoDelta** [comment]
nun ok , dann werde ich jetzt erstmal warten bis die Lösung von Euch bereitgestellt wird - dann testen und berichten…
wird es dann nen offizielles komplettes update geben oder nur die Files zum manuellen updaten???

**Comment by therouv** [comment]
Wird als entsprechendes Update auf MagentoConnect hochgeladen. Du kannst aber auch dann hier die entsprechende Version herunterladen.

**Comment by OrinocoDelta** [comment]
Hallo Rouven,

der Alex nochmal hier…

Ich frage mal einfach, kann ich über Github Firegento German komplett laden und via FTP in Magento ersetzen bzw. überschreiben???
Gefahrenlos? oder sollte ich die Änderungen manuell machen? also aus den Commits ???

Liebe Grüße alex aus Mainz…

---

mittlerweile habe ich die Umsetzung der Rechnunsanzeige umgesetzt… PDF Rechnung enthalten nun die richtigen Merkmale…. ;-)

Am 24.07.2012 um 09:11 schrieb Rouven Alexander Rieker reply@reply.github.com:

**Comment by OrinocoDelta** [comment]
Hallo anbei nochmal meine letzte E-Mail, und jetzt nochmal was neues…

Ich habe nun via FTP den letzten Stand jetzt im Shop überschrieben bzw. hochgeladen…
Das einzige was ich sehe ist die Option bei den Attributen:
Sichtbar im Bestellprozess

Schonmal sehr sehr wertvoll…

Ich hätte eine Bitte - kannst Du mir evtl. sagen ob es überhaupt für ein eigenes Theme +
den Nicht Standard Onepage Checkout funktionieren sollte?

Wollte jetzt bei Github dazu kein neues Fass aufmachen, bisher sehe ich aber keine
Veränderung auf meinem Developer Shop ;-(

Könntest Du evtl. ne kleine Zusammenfassung posten, was jetzt alles im Update enthalten ist
und was nicht?

Gerade eben habe ich noch eine Sache entdeckt….

firegento-germansetup soll automatic Meta Daten generieren ???
Wo kann das aktiviert werden….

Nachdem ein Produkt angelegt ist, existieren keine Meta Daten …

Liebe Grüsse aus Mainz…

Am 27.07.2012 um 12:23 schrieb OrinocoDelta hello@now-x.com:
