### ISSUE TITLE
Endlosschleife bei Katalogpreisregeln

### ISSUE THREAD

**Issue by riconeitzel** [firegento/firegento-germansetup#39]
Ich hatte eben des Problem, dass bei aktivierten Katalogpreisregeln der Code an irgendeiner Stelle in eine Endlosschleife rasselt. Ist nur dadurch zu beheben, dass man GermanSetup deaktiviert.

Letzter Schritt vor dem Fehler war: Aktivieren einer Katalogpreisregel. Das Löschen und Austragen der Preisregel hatte keine Besserung zur Folge…

**Comment by therouv** [comment]
Hängt vermutlich mit #43 zusammen. Müsste man noch mal prüfen.
