### ISSUE TITLE
Mage registry key "_singleton/germansetup/observer" already exists

### ISSUE THREAD

**Issue by hir0pr0tagonist** [firegento/firegento-germansetup#41]
Hallo Firegento Team,

Erst einmal vielen Dank fuer das geniale Modul !
Ich habe Magento 1.7.0.1 im Einsatz und alles funktioniert problemlos, allerdings bekomme ich den Fehler "Mage registry key "_singleton/germansetup/observer" already exists" wenn ich System/Tools/Compilation aktiviere. Kompilieren laesst es sich, aber wenn ich es aktiviere, kommt dieser Fehler. Laesst sich das irgendwie vermeiden oder mache ich was falsch ?
Falls ihr mehr Details braucht, bitte einfach kurzes Update.

Danke im voraus,
hiro

**Comment by therouv** [comment]
Hi,

hatte es gerade eben einmal getestet (allerdings 1.7.0.2) und da hat das reibungslos geklappt. Ist auch eher unwahrscheinlich, da das bedeuten würde, dass der Observer zur gleichen Zeit ein zweites Mal instanziiert werden müsste. Anyways, werde gleich noch etwas pushen was den "Fehler" beheben sollte.

Grüße

**Comment by hir0pr0tagonist** [comment]
Hallo Rouven,

Der Fehler lag bei mir: ich hatte vor der Installation des German Setup vergessen, den Cache auszuschalten und den Compiler-Cache zu leeren. Habe beides nachgeholt, dann German Setup nochmal neu installiert, und siehe da: es klappt jetzt alles !

Danke und Gruesse,
hiro
