### ISSUE TITLE
Email Templates Preis Darstellung nicht inklusive MwSt.

### ISSUE THREAD

**Issue by OrinocoDelta** [firegento/firegento-germansetup#44]
Hallo ist das nur bei mir so?

In den Emails (Neue Bestellung / Neue Rechnung / etc.) wird der Preis wie folgt dargestellt:

Artikelpreis  --> inkl. MwSt.
Zwischensumme --> ohne MwSt.
Versand & Bearbeitung --> ohne MwSt.
inkl. 19% MwSt. --> RICHTIG
Endsumme --> Richtig

Das ganze obwohl im Admin die Anzeigeeinstellung für Bestellungen, Rechnungen, Gutschrift auf "inklusive Steuern"
eingestellt ist…

Wie kann das sein? Im Kunden - Backend stimmt auch alles, auch in den PDF-Rechnungen via E-Mail stimmt alles…
Jemand eine Idee wo ich ansetzen kann?

Anbei Screenshots:

https://skitch.com/orinocodelta/ek4eb/olis-teile-shop.de-rechnung-nr-re120803-181120-fur-bestellung-nr-be120802-104215-eingang-1

https://skitch.com/orinocodelta/ek4er/olis-teile-shop.de-autoteile-reifen-felgen-and-mehr-konfiguration-system-olis-teile-shop.de-autoteile-reifen-felgen-and-mehr-magento-administration

https://skitch.com/orinocodelta/ek4eg/olis-teile-shop.de-rechnung-nr-re120803-181120-fur-bestellung-nr-be120802-104215-eingang-2

**Comment by mklooss** [comment]
Kann den Fehler nicht bestätigen

**Comment by avstudnitz** [comment]
Kann ich auch nicht nachvollziehen. Scheint ein Konfigurationsproblem in dem einzelnen Shop zu sein.

**Comment by ghost** [comment]
Hallo,

genau dieses Problem tritt auch jetzt bei uns auf...
