### ISSUE TITLE
Umgestaltung Checkout-Seite läuft nicht unter Magento 1.4.1.1

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#45]
Weder in meiner lokalen Testinstallation noch bei einem Nutzer, der mir eine Email geschrieben.

**Comment by mklooss** [comment]
Das ist soweit korrekt, dass es nicht geht, da die Struktur leider deutlich abweicht vom Magento ab 1.5...

sei es in der layout.xml oder aber in den Models selber...

**Comment by avstudnitz** [comment]
Magento < 1.6 wird von den neueren German Setup-Versionen nicht mehr unterstützt.
