### ISSUE TITLE
Nur ich? Link mit Versandkosten verschwunden

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-germansetup#50]
Hallo,

is it just me?
aktuellste Version und Magento 1.7.0.0.
"Inkl. 19% MwSt." sowohl in der Produkt wie auf Kategorieansicht. Hier fehlt der Versandkostenlink.
Jemand eine Idee wo der hinsein könnte? :D

**Comment by therouv** [comment]
Ist bei dem Punkt "CMS-Seite für Versandkosten" unter "System -> Konfiguration -> Katalog -> Katalog -> Preis" die entsprechende Seite ausgewählt? Falls nein, bitte mal testen..

**Comment by easyMaxi** [comment]
Ah super!
War keine Seite ausgewählt. Scheint beim Update verloren gegangen zu sein.

Danke!
