### ISSUE TITLE
[+FEATURE] Versandkosten Table Rates, inkl. MwSt.

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#54]
Wenn man in den "Table Rates" bspw. ab "50 €" Versandkostenfrei haben will, muss man hier mit dem Wert ohne MwSt. rechnen.
Wenn man Artikel hat mit NUR einem MwSt.-Satz - 19 % - kein Problem ist, aber wenn man 7% und 19% o.ä.
ist natürlich die Berechnung falsch.

Habe hier zu bspw. den Beitrag im Magento Forum gefunden:
http://www.magentocommerce.com/boards/viewthread/30924/P15/

ggf. kann man dieses auch mit aufnehmen

**Comment by mklooss** [comment]
Sample Fix:
https://github.com/mklooss/Loewenstark_TableratesTax

**Comment by dakira** [comment]
Versandkostenfreiheit kann man doch simpel über die Warenkorb Preisregeln definieren: Wenn Warenkorbzwischensumme > $PREIS dann keine Versandkosten. Speichern und fertig.

**Comment by mklooss** [comment]
das ist schon richtig, aber nicht unbedingt Kundenfreundlich, da im PaymentStep immer noch der "Versandkostenpreis" angezeigt wird, und auf der Review Seite richtig dargestellt wird.

Zu dem ist der Thementitel so nicht mehr richtig, da es nicht direkt um Versandkostenfrei geht, sondern um die Richtige Zwischensumme in den Tablerates, gerade bei Shops mit 2 verschiedenen MwSt'n.

**Comment by dakira** [comment]
Hm. Also bei mir wird sowohl im Warenkorb (wenn man den Versandkostenrechner nutzt) wie auch beim Abschluss der Bestellung immer korrekt 0 Euro Versandkosten angezeigt. Der Bug mit der MwSt bleibt natürlich.

**Comment by therouv** [comment]
Ist nicht zwingend ein Feature für German Setup. Interessenten können das genannte Modul von @mklooss nutzen.
