### ISSUE TITLE
can't clone with modman

### ISSUE THREAD

**Issue by arosenhagen** [firegento/firegento-germansetup#55]
möchte man mit

``` bash
modman clone git://github.com/firegento/firegento-germansetup.git 
```

die Extension installieren, werden die Symlinks alle korrekt gesetzt - aber die Seiten im Backend bleiben leer. Die manuelle Installation (kopieren der Dateien) funktioniert einwandfrei.
Das Problem besteht mit einigen anderen modman-extensions ebenfalls - noch habe ich den Grund hierfür aber nicht gefunden.

**Comment by therouv** [comment]
Hallo,

das ist kein Problem von GermanSetup, sondern liegt in einer Konfigurationseinstellung von Magento. Unter "System -> Konfiguration -> Entwickleroptionen -> Vorlagen Einstellungen" gibt es die Option "Symlinks (Verknüpfungen) erlauben". Diese Feld muss auf "Ja" gesetzt werden, so dass die erzeugten Symlinks von modman auch korrekt funktionieren.
