### ISSUE TITLE
Fehlerhafte JS-Fehlermeldung im Checkout

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#58]
Support-Anfrage per Email:

"ich habe ein Problem, vielleicht kannst du mir weiterhelfen.
Beim Bezahlprozess zum Schluß wenn der Kunde die AGBs und den Widerruf bestätigen soll und die Checkboxen aktiviert sind.
Kommt immer noch eine Fehlermeldung vom Javascript, das diese bestätigt werden sollen."

**Comment by mklooss** [comment]
Ja gute Frage, welche Stand hat der Kunde installiert?
Ist es mit dem Part von mir... dann muss überprüft werden, ob der Helper nicht 2x Überschrieben wird.

**Comment by avstudnitz** [comment]
Keine Antwort bis jetzt.
