### ISSUE TITLE
Öffnen der AGB in neuem Tab

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#59]
Wenn man im Checkout AGB etc. in neuem Fenster öffnet, wird der Beginn des Checkout angezeigt.

Ich denke man kann hier einfach das href Attribut statt auf "#" auf die agreements URL entsprechend setzen - spricht etwas dagegen?

**Comment by avstudnitz** [comment]
Klingt gut :-) Aus meiner Sicht spricht nichts dagegen.
