### ISSUE TITLE
Anpassung der Emails

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#6]
z.B. Verwendung des gleichen Templates für Gäste und registrierte Benutzer

**Comment by mklooss** [comment]
E-Mail für Passwort vergessen ist auch veraltet, in 1.6 wurde dieses geändert.

ab 1.6 wird ein Link gesendet, davor war das Passwort direkt in der E-Mail enthalten.

**Comment by mklooss** [comment]
Wegen den E-Mail Templates, da sich ja immer wieder etwas ändert.

Wie wäre es, wenn man in "Mage_Core_Model_Translate", die Methode "getTemplateFile" überschreibt.

Wenn $type ist email schaue in den Ordner email von German Setup und dann erst in den Default Order?
"germansetup/email", so muss man die E-Mail Templates nicht importiert und hat sie Lokalisiert.

als grobes Beispiel:

```
if( $type=="email" ) {
   $type = "germansetup/email";
}
```

nur so ein Gedanke

Würde auch Probleme mit dem Locale Package beheben und wenn sich E-Mail Templates ändern auch.

**Comment by millejano** [comment]
Kann in der 1.7.0.0 das beschriebene Verhalten das es nur eine Passwort Mail gibt bestätigen, es sollte dort 2 Vorlagen geben (Passwort vergessen und Passwort Erinnerung).

Weiterhin frage ich mich ob man nicht mit dem German_LocalePack_de_DE Projekt zusammenarbeiten könnte, denn dieses stellt schon angepasste E-Mail-Templates bereit. Ich gehe davon aus, dass eure Templates zusätzliche Blöcke enthalten weswegen ihr eigene verwendet.

Lösung: Man könnte z.B. eine vorherige Abfrage einbauen, depend germanSetup um z.B. gs_revocation erst beim vorhanden sein der Extension hinzuzufügen. Die Pflege der E-Mail Templates würde dann trotzdem über German_LocalePack_de_DE erfolgen.

Weiterhin würde ich auch für germansetup/imprint/email_footer.phtml ein cms-block ohne template verwenden, ist besser über Statische Blöcke im Backend pflegbar.

Für Multi-Shops mit mehreren Sprachen, hat sich zusätzlich das Anlegen eines email headers und footers (jeweils ein statischer Block) als praktikabel erwiesen. Diese können dann auf StoreView-Ebene abgeändert werden (Text/Grafik) und man verwaltet nur die E-Mails pro Sprache (2 Shops mit 2 Sprachen, 50% zeit gespart).

Grüße, millejano

**Comment by mklooss** [comment]
Yep, das war auch mein Gedanke deshalb der Post oben...
Leider habe ich heute auch gemerkt, dass die Änderung meinerseits bezüglich Passwort vergessen an sich so nicht richtig war... da Magento hier 2 neue anders benannte Templates "erwartet". (wie von dir erwähnt)

Neu sind die "account_password_reset_confirmation.html" und "admin_password_reset_confirmation.html"
Obsolet sind die "admin_password_new.html" und "password_new.html"

Die Templates unterscheiden sich in der Hinsicht von den Locale Variante, da diese hier noch den Footer beinhalten (AGB / Widerruf in den Bestellemails).

Eine Überprüfung an sich schön und gut... aber wenn die Dateien schon vorhanden sind meckert der Connect Manager von Magento...
Daher war oben ja mein Vorschlag ggf. die Core Class zu überschreiben und eine Abfrage mit einzubauen...
Da die Templates von GermanSetup im Unterverzeichnis liegen.

Ich persönlich bevorzuge aber die Trennung, da wir auch Internationale Shops erstellen, wo GermanSetup oder anderes nicht benötigt wird.

**Comment by avstudnitz** [comment]
Emails werden ab sofort vom Sprachpaket verwendet.
