### ISSUE TITLE
Div-Tag um Preisinfos

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-germansetup#60]
Hallo zusammen,

ich würde sehr dafür plädieren, um die Preisinformationen ein zusätzliches Div-Tag zu platzieren. Momentan ist es unmöglich, nur anhand von CSS/Templates den Preis inklusive Steuer- und Versandinfos links und den Warenkorb-Button rechts floaten zu lassen (oder ich bin zu doof :-) ). Die werden alle im selben div gerendert... Deshalb würde ich in der FireGento_GermanSetup_Block_Catalog_Product_Price::_toHtml Methode zwei Zeilen hinzufügen:

``` php
/**
 * Add content of template block below price html if defined in config
 *
 * @return string
 */
public function _toHtml()
{
    $html = trim(parent::_toHtml());

    if (empty($html) || !Mage::getStoreConfigFlag('catalog/price/display_block_below_price')) {
        return $html;
    }

    if ($this->getTemplate() != $this->_tierPriceDefaultTemplate) {
        $html = '<div class="outer-price-box">' . $html; // NEU
        $html .= $this->getLayout()->createBlock('core/template')
            ->setTemplate('germansetup/price_info.phtml')
            ->setFormattedTaxRate($this->getFormattedTaxRate())
            ->setIsIncludingTax($this->isIncludingTax())
            ->setIsShowShippingLink($this->isShowShippingLink())
            ->toHtml();
        $html .= '</div>'; // NEU
    }

    return $html;
}
```

Wenn das allgemeine Zustimmung findet, mache ich auch, falls gewünscht, gerne ein Pull-Request dafür...

Viele Grüße
Simon

**Comment by avstudnitz** [comment]
Du könntest das Div auch einfach in der germansetup/price_info.phtml einbauen.
Ansonsten finde ich die Idee gut :-)

**Comment by sprankhub** [comment]
Nein, das reicht leider nicht aus :-) Da kann ich ja nur ein Div um die neu hinzugefügten Steuer- und Versandinfos packen... Ich brauche das div aber um die Standard Preisbox UND den neuen Steuer-/Versandinfos...

**Comment by therouv** [comment]
Das wäre dann aber einen Fall vom individuellen Templating eines Shops. Prinzipiell sollten wir aber keinen HTML-Code in PHP-Blocks reinbringen.

**Comment by sprankhub** [comment]
"Fall vom individuellen Templating eines Shops"... Das ist schon richtig, ist an der Stelle aber leider nicht mit Templates zu lösen... Das ist halt etwas schade... Ich fände es gut, wenn man dem Entwickler wenigstens die Möglichkeit dazu gibt... Aber ist natürlich eure Sache :-)

**Comment by mklooss** [comment]
ggf mit einem Event in der Methode? welches am Ende vor "return $html;" kommt?
übergabe $this und $html

**Comment by sprankhub** [comment]
Wenn das für alle akzeptabel ist, gerne - guter Vorschlag!

**Comment by mklooss** [comment]
was aber auch geht, ist den Block zu Überschreiben... hatte ich gerade, da ich ein Upgrade auf 1.7 mache...
der Ausgangsshop hat MRG...

```
class [Kundename]_Main_Block_GermanSetup_Catalog_Product_Price
extends FireGento_GermanSetup_Block_Catalog_Product_Price
{
    public function _toHtml()
    {
        $html = trim(parent::_toHtml());
        if (empty($html) || !Mage::getStoreConfigFlag('catalog/price/display_block_below_price')) {
            return $html;
        }
        if ($this->getTemplate() != $this->_tierPriceDefaultTemplate) {
            $html .= $this->getLayout()->createBlock('core/template')
                ->setTemplate('local/product/list/delivery_time.phtml')
                ->setDeliveryTime($this->getProduct()->getDeliveryTime())
                ->setProduct($this->getProduct())
                ->toHtml();
        }
        return $html;
    }
}

<blocks>
            <germansetup>
                <rewrite><!-- FireGento_GermanSetup_Block_Catalog_Product_Price //-->
                    <catalog_product_price>[Kundenname]_Main_Block_GermanSetup_Catalog_Product_Price</catalog_product_price>
                </rewrite>
            </germansetup>
        </blocks>
```

(nicht wundern, erstelle eigtl immer eine Kunden Extension ^^)

**Comment by sprankhub** [comment]
Danke dir, ist sicherlich auch eine Option. Allerdings ist ein Event natürlich immer schöner :-) Wenn da also Andreas und Rouven nichts dagegen hätten...

**Comment by therouv** [comment]
Diskussion wird in #65 weitergeführt, so dass dieses Issue geschlossen werden kann.
