### ISSUE TITLE
Setup Wizard berücksichtigt eigene Steuerklassen nur bedingt

### ISSUE THREAD

**Issue by ebtc** [firegento/firegento-germansetup#61]
Wir haben 2 Arten der Steuerklassen: Güter und Waren. Nachdem GermanSetup installiert ist findet der Wizard auch selbige und bietet unter dem Punkt "Produktsteuerklassen neu zuweisen" auch diese an. Leider fehlen diese aber im Dropdown, so dass nur Güter vorhanden sind (0%, 7%, 19%).

**Comment by mklooss** [comment]
Du musst die Daten aus dem Wizard nicht Importieren.

Wenn Ihr es anderes macht, ist das bei euch so... aber ich denke mal bei 90 % der Deutschen Shops passt dieses...

Denke daher sollte es passen.
