### ISSUE TITLE
Strings (Required) auf /admin/checkout_agreement/ Englisch

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#62]
Nur reproduzierbar mit Developer Mode an.

Dort erscheint dann "Required" statt "Erforderlich"

Der String ist in der FireGento_GermanSetup.csv nicht vorhanden.

**Comment by amenk** [comment]
siehe auch #63

**Comment by therouv** [comment]
Ist ja bereits gemerged.
