### ISSUE TITLE
PDF Ausdrucke im Admin Bereich

### ISSUE THREAD

**Issue by ebtc** [firegento/firegento-germansetup#67]
Hallo,

Wen Rechnungen über den Admin Bereich gedruckt werden ist die Gestaltung der pdfs wie beim Standard (also schlecht). Die Emails sind aber formatiert (dann da aber der Anhang nicht).

Ist das so gewollt, dass keine PDFs gestaltet sind?
Wenn ja, kann man das ggf. optional anfügen?

Gruß.

**Comment by therouv** [comment]
Hallo,

das ist gewollt so, da das unserer Meinung nach nicht direkt mit integriert sein soll und je nach Shop-Betreiber auch unterschiedlich gehandhabt wird. Viele Shop-Betreiber setzen auch andere Module ein bzw. benötigen keine PDF-Gestaltung, da z.B. alles über das ERP-System abgewickelt wird.

Wir werden hierfür aber ein getrenntes Modul zur Verfügung stellen. Der aktuelle Entwicklungsstand diesbezüglich kann hier eingesehen werden: https://github.com/firegento/firegento-pdf/

Viele Grüße,
Rouven

**Comment by ebtc** [comment]
danke!
