### ISSUE TITLE
Zugriff auf aktuelles Produkt aus price_info.phtml

### ISSUE THREAD

**Issue by rarog** [firegento/firegento-germansetup#68]
Ich würde für spezielle Anpassungen gern auf das Objekt des aktuellen Produkts zugreifen, allerdings führt "$this->getProduct()" in die Leere. Geht das überhaupt irgendwie sauber, oder muß in FireGento_GermanSetup_Block_Catalog_Product_Price explizit das Produkt zugewiesen werden, damit man darauf zugreifen kann?

**Comment by mklooss** [comment]
ggf mal probiert? Mage::registry('current_product');

**Comment by rarog** [comment]
Funktioniert innerhalb des Produkt-Templates, crasht aber natürlich die Ausgabe der Produkte in der Kategorie, da das nicht gesetzt ist. Das einzige, was ich als Workaround erreichen konnte, war noch "->setProductId($this->getProduct()->getId())" reinzufriemeln innerhalb von "_toHtml", das ist aber etwas, was verlorengehen würde mit Modulupdate.

**Comment by mklooss** [comment]
wenn würde ich die Collection übergeben, sprich

```
->setProduct($this->getProduct())
```

dann kannst du im Template ->getProduct()->getId() machen, deine Variante würde nur Unnötige Abfragen auf die Datenbank feuern...

Wenn du dann im Template

```
Mage::getModel("catalog/product")->load($this->getProductId())->getAttributeCode()
```

machen würdest...

**Comment by rarog** [comment]
Hab ich getestet, funktioniert leider nicht korrekt. Zusätzliche Attribute werden innerhalb der Kategorieansicht nicht geladen, somit muß ich so oder so nochmal einen DB-Zugriff ausführen, nur innerhalb der Produktansicht wird wirklich alles geladen.

**Comment by mklooss** [comment]
Stell im Attribute: "In Kategorieansicht verwenden" auf "Ja" dann sollte es gehen ;-)

**Comment by rarog** [comment]
Oh, danke, das bringt natürlich die Lösung. Wird das mit "setProduct" auch in den offiziellen Modulecode übernommen, oder ist das zu spezifisch und ich sollte lokal einen Patch pflegen?

**Comment by therouv** [comment]
Bitte selbst einen lokalen Patch pflegen. Zu speziell für GermanSetup.

**Comment by zebulon60** [comment]
Hallo zusammen!
@mkloos : vielen dank für die fachlichen Ausführungen und vielen Dank an @rarog für die Frage.

Ich habe ein ähnliches Problem: ich möchte in der price_info.phtml bei jedem Artikel den Wert eines neuen Attributes ausgeben lassen. Leider erhalte ich bislang nur entweder leere Ausgaben oder eine 'call on a non-Object' Fehlermeldung. Den guten Tip "In Kategorieansicht verwenden" auf "Ja" zu stellen habe ich natürlich berücksichtigt.

Leider bin ich fachlich nicht weit genug versiert, um den Code
"->setProduct($this->getProduct())"
aufzurufen, denn mir fehlt die Info, wie dieser Code in der ganzen Zeile lautet und vor allem, in welche Datei er hineingehört. In die 'price_info.phtml' ja sicher nicht, oder? 
Denn dort könnte ich dann später mit 
"Mage::getModel("catalog/product")->load($this->getProductId())->getAttributeCode()"
mein Attribut-Value ausgeben, hoffe ich.

Jeder Tip und Hinweis wird bei mir große Freude auslösen! :-)

Cheers,
Johannes

**Comment by rarog** [comment]
Das wäre der korrekte Code. Wenn das Attribut innerhalb des Codeblocks von price_info.phtml ausgegeben werden soll, dann gehört der Code auch dahin. Das sollte dann auf jeden Fall genau so funktionieren.

**Comment by Schrank** [comment]
Um weitere Attribute zu laden kannst du entweder im Backend Sichtbar im Listing auf yes stellen für das Attribut, oder es einfach in eine config.xml werfen an diese Stelle: `/config/frontend/product/collection/attributes` dann wird es geladen und du kannst das attribut auch in produkten benutzen, die aus einer collection kommen

**Comment by mklooss** [comment]
Im Template wäre richtig "$this->getProductId()->getAttributeCode()" und es muss sichergestellt werden, ob das Attribute in der Colleciton vorhanden ist, wie Schrank schon schrieb, per XML Defintion oder aus dem Backend (bei beiden Änderungen muss ggf. der Flat Tables Index neugebaut werden.)

**Comment by zebulon60** [comment]
He Leute,
herzlichen Dank für Eure Antworten! Mittlerweile habe ich allerdings das Ganze ohne die price_info.php gelöst - diese Tipps werde ich mir aber trotzdem merken, denn sowas werde ich garantiert bald nutzen können. Also nochmals Dank!

Hier aber dennoch meine Lösung für die list.phtml und auch andere Dateien, z.B. für die Auflistung von manuell gesteuerten Sonderangeboten. In meinem Fall ging es um die Darstellung der je nach Storeview (DE, AT, etc.) unterschiedlichen Versandkosten; das Custom Attribut ist gleichlautend:

```
<span class="tax-details">Inkl. 19% MwSt., zzgl. <span class="shipping-cost-details">
<? echo number_format($_product->getData('versandkosten'),2,',','.').' Euro'; ?> 
Versandkosten </span></span>
```

**Comment by Schrank** [comment]
Sei vorsichtig mit dem `<?`, nicht dass das mal aus ist.

http://php.net/manual/en/ini.core.php#ini.short-open-tag
