### ISSUE TITLE
Steuersatz Versandkosten nach dem größten Anteil an Produktwerten

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-germansetup#69]
In Deutschland wird (kann) der Steuersatz den man auf die Versandkosten bezahlt, abgeleitet werden aus dem Steuersatz des größten Anteils an Steuern der Produkte.

Es ist bereits so, dass der höchste Steuersatz im Versand genommen wird, ein Beispiel in dem man nach dem aktuellen Schema dennoch Geld dem Staat "schenkt":

Beispiel:
Produkt 1 (7%) 10€
Produkt 2 (10%) 5€
Steuersatz im Verand nach aktuellem Modell: 19%
sollte aber 7% sein.

**Comment by tobi-pb** [comment]
Ich frage mal ganz doof: Hast du eine Quelle dafür? Ich höre von unterschiedlichen Steuerberatern immer mal unterschiedliche Dinge. Da du es aber konfiugierbar gemacht hast sollte das ja kein Problem sein.

Einzige Frage: Was nehmen wir als Standard?

**Comment by Schrank** [comment]
Quelle: Kunde

Die Quellen, die ich gerade im Netz bemüht habe, z.B. [Onlinesteuerrecht.de](http://www.onlinesteuerrecht.de/home/index.php?option=com_content&task=view&id=28&Itemid=33) sagen man müsse das nach dem Verhältnis aufteilen.

Korrigiert mich, aber das ist alles andere als leicht zu realisieren.

Ich würde es daher einfach so übernehmen, kann ja jeder mit seinem Steuerberater klären, ob er das so will.

**Comment by Schrank** [comment]
Ich hätte hier noch ne Quelle für "Man kann es so machen, wie die Erweiterung vorsieht":
http://www.modified-shop.org/forum/index.php?topic=19813.msg185103#msg185103

**Comment by therouv** [comment]
Finde die Idee gut und kann man meiner Meinung nach gerne so übernehmen. Tendenziell muss das jeder Shop-Betreiber dann sowieso noch einmal selbst mit seinem Steuerberater abklären.

Standardmäßig sollte (wie bisher auch) der Magento-Standard (also die konfigurierbare Versandsteuerklasse) verwendet werden.

**Comment by Schrank** [comment]
Ah, ja, das hatte ich vergessen Standard würde ich natürlich auch nicht ändern wollen! :)

**Comment by therouv** [comment]
Wurde bereits gemerged. Issue wird geschlossen.
