### ISSUE TITLE
Darstellung von CMS-Blöcken in den Checkout Agreements (z.B. AGB)

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#7]
gemäß http://www.dannygerst.de/magento/rendering-a-cms-block-in-agreements/

**Comment by therouv** [comment]
Hallo Andreas,

wurde bereits in Commit 964a88a100d691317c2e6aa91ef8b2c9d9244465 final implementiert.

Viele Grüße,
Rouven
