### ISSUE TITLE
Multi Store Fähigkeit

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-germansetup#74]
Ist die Extension Multi Store fähig?

Angenommen ich habe einen Shop welcher in mehreren Ländern verkauft - betreffen da die diversen Anpassungen nur den deutschen Store?

**Comment by mklooss** [comment]
die Einstellungen werden auf Default Ebene geschrieben vom Modul... kannst du aber auch alles Händisch auf der Website oder StoreView Ebene einstellen.

**Comment by amenk** [comment]
Dann ist das hiermit ein Feature Request :-)

**Comment by amenk** [comment]
Wie handhabt das eigentlich MRG ?

**Comment by therouv** [comment]
MRG ändert auch nur den Default Scope.

**Comment by drlrdsen** [comment]
Das stimmt so auch nur bedingt. Auch, wenn du nach Österreich, Frankreich oder Groß-Britannien verkaufst, unterliegst du in deiner französischen und englischen Seite zunächst mal deutschem Recht, so keine Tochterfirma vorliegt. Ich denke, das ist allerdings eine Geschichte, die bei 95% aller normalen Shops nicht vorliegt. Dementsprechend wäre das für mich ein Customizing, das in der Standard-Version nichts zu tun hat (weil es die Verarbeitung verkompliziert). Wenn überhaupt sollte das nicht auf StoreView, sondern auf Webseiten-Ebene geändert werden.

**Comment by avstudnitz** [comment]
Versand aus mehreren Ländern werden wir nicht unterstützen. Angedacht ist das Anlegen von Email-Templates nach Store für mehrsprachige Shops, sowie das Anlegen von CMS-Blocks und -Seiten für mehrere StoreViews.

**Comment by giorgiojob** [comment]
Habe ein etwas anderes Problem. Unser Shop ist Multilingual und ich bekomme im Checkout bei AGB und Widerruf neben den Kästchne zum Aktzeptieren nur den deutschen Text angezeigt, also: Allegmeine Geschäftsbeidungen müssen akzetiert werden etc. Dieser Text lässt sich nicht übersetzen und in den MAGE dateien habe ich ebenfalls nichts gefunden. Sieht allerdings wenn jemand aus England kommt etwas seltsam aus in deutsch. Was mache ich falsch bzw. wo kann ich den Text übersetzten. Alles andere funzt SUPERGUT, vielen Dank auch für das Modul!!!

**Comment by amenk** [comment]
@giorgiojob Du musst "Unter Verkäufe -> Bestellbedingungen" einzelne Einträge für jede Übersetzung anlegen und den Eintrag unter "Checkbox Text" entsprechen übersetzen.

**Comment by giorgiojob** [comment]
Mein Gott, ich Danke Dir vielmals!! Da hätte ich ja auch echt selbst drauf kommen können, aber Wald, Bäume?! Vielen, vielen Dank für den Hinweis ist ja klar, aber da hätte ich vermutlich selbst noch eine Stunde rumgewühlt, bis mir das wieder eingfallen wäre. Nochmals Danke für den schnellen und kompetenten Tip!

**Comment by amenk** [comment]
Sollte das wirklich closed sein? Andreas schreibt ja "Versand aus mehreren Ländern werden wir nicht unterstützen. Angedacht ist das Anlegen von Email-Templates nach Store für mehrsprachige Shops, sowie das Anlegen von CMS-Blocks und -Seiten für mehrere StoreViews."
Gibt es dazu ein anderes issue?

**Comment by riconeitzel** [comment]
wenn ich oder du zeit haben oder hast, mach doch bitte mal zwei getrennte feature-request-issues dafür auf. :-)

**Comment by avstudnitz** [comment]
@amenk Das ist jetzt in MageSetup umgesetzt (https://github.com/firegento/firegento-magesetup/issues/4). Ein Test der Funktionalität wäre super :-)
