### ISSUE TITLE
Version Tags in Git

### ISSUE THREAD

**Issue by tobi-pb** [firegento/firegento-germansetup#75]
Wollen wir nicht die Versionen von German-Setup mit Tags versehen? So ließe sich das in packages.firegento.com nutzen.

**Comment by therouv** [comment]
Wird prinzipiell schon von @avstudnitz oder mir gemacht. Siehe https://github.com/firegento/firegento-germansetup/tags

Viele Grüße,
Rouven 

// von meinem iPhone gesendet
