### ISSUE TITLE
[Buttonlösung] Zusätzliche Texte - Zoll

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#76]
Moin,

bei der Buttonlösung müssen ja auch noch ggf. Informationen angefügt werden.
Einerseits die Zollhinweise, wenn ShippingAddress im Ausland ist.

Andererseits die 2 € Aufschlag von der DHL für Nachnahmegebühren.
weiss nicht ob es noch mehr gibt.

Was auch weg muss ist, der Punkt "Artikel vergessen, zum Warenkorb".
Einerseits eh ggf. ein Conversion Killer? und laut Trusted Shops wohl nicht richtig.

**Comment by therouv** [comment]
Hallo,

das ist ein Shop-spezifisches Thema und muss je nach Installation unterschiedlich gehandhabt werden. Wir haben hierfür ja ein eigenes Feld in der System-Konfiguration implementiert, wo man einen entsprechenden Text dann hinterlegen kann.

Viele Grüße
