### ISSUE TITLE
Datum der Newsletterregistrierung speichern

### ISSUE THREAD

**Issue by therouv** [firegento/firegento-germansetup#78]
Wenn ein Kunde sich zu einem Newsletter anmeldet, sollte man auch noch den entsprechenden Zeitpunkt mit in der Datenbank speichern um im Zweifelsfall auch die Anmeldung nachweisen zu können.

**Comment by avstudnitz** [comment]
Brauchen wir da eine History, oder reicht das vorhandene DB-Feld change_status_at (Tabelle newsletter_subscriber)?

**Comment by therouv** [comment]
Ich würde 2 Felder machen:
- created_at
- updated_at

So haben wir jeweils die richtige Information.

**Comment by avstudnitz** [comment]
Praktisch ja. Theoretisch wissen wir nicht genau, zu welchem Zeitpunkt er welchen Status hatte, wenn er sich wiederholt an- und abgemeldet hat.

**Comment by therouv** [comment]
Es wird nun jede Status-Änderung in eines Newsletter Abonnenten gespeichert, so dass ein Shop-Betreiber genau nachvollziehen kann, wann ein Abonnent sich anmeldet/Anmeldung bestätigt/abmeldet/.. Sollte ein Abonnent gelöscht werden, bleibt die Historie dennoch bestehen.
