### ISSUE TITLE
Viele Checkboxen im Checkout nach MRG Deinstallation und German Setup Installation

### ISSUE THREAD

**Issue by cphilipp** [firegento/firegento-germansetup#79]
Nachdem MRG deinstalliert und German Setup installiert wurde, gibt es ganze vier Checkboxen im Checkout auf der Bestellübersichtsseite. Das sollten... mindestens halbiert werden! ;)

**Comment by mklooss** [comment]
genauer spezifizieren, was mit "mehrere Checkboxen" gemeint? ggf. Screeny

**Comment by cphilipp** [comment]
Screenshots nerven ein bisschen bei Github... es ist ganz einfach:
Mit vielen Checkboxen ist gemeint, dass die AGB- und Widerruf-Checkboxen sowohl von MRG als auch von GermanSetup sichtbar sind.
Bei der Installation von GermanSetup sollte meiner Meinung darauf geachtet werden, dass vorher die Bestellbedingungen geleert werden.

**Comment by mklooss** [comment]
ah okk. das meinst du, denke, nicht, dass es relevant ist, da du dieses beim "Setup" einstellen kannst.

**Comment by riconeitzel** [comment]
Ich würde die nicht leeren, da sonst auch bestellbendingungen verschwinden, die vielleicht nicht ersetzt werden sollen. Alternative: Auswahlliste der bestehenden Bestellbedingungen zum Löschen bei der Installation?
