### ISSUE TITLE
Entfernen der Meldung

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#8]
Wenn Cache aktiviert ist, verschwindet die Meldung nicht. Entweder andere Methode wählen, um "gelesen"-Flag in der Config zu speichern, oder einmal Cache aktualisieren

**Comment by tobi-pb** [comment]
Welche Meldung meinst du? Dann kann ich auch mal was tun :D

**Comment by avstudnitz** [comment]
Die auf http://www.avs-webentwicklung.de/fileadmin/images/ScreenShot730.png dargestellte... "German Setup wurde installiert. Klicken Sie hier..."
