### ISSUE TITLE
Shipping from other countries 

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-germansetup#80]
From MagentoConnect private message to team firegento:

Hello,

I installed your addon for my Magento Shop. Buf the “Versand aus” value doenst change. When I select “Österreich” and klick on “German setup ausführen” it wont change. It always show me “Deutschland” as the selected valued. The checkbox doenst change too.

Regards
Tim Heise

**Comment by therouv** [comment]
Kann doch auch rein theoretisch nicht sein, da die Werte der Setup-Form nicht gespeichert werden, sondern das Formular für die nächste Bearbeitung wieder zurückgesetzt wird.

**Comment by riconeitzel** [comment]
Konnte das mal einer nachvollziehen?!

**Comment by therouv** [comment]
Nein. Deshalb einmal geschlossen.

**Comment by r8r** [comment]
bei mir auf 1.7.0.2 zeigt sich dasselbe Verhalten wie bei avstudnitz.
Es gibt leider keine einfache möglichiet um zu prüfen, ob "Österreich" gespeichert wurde und die Auswahl nur UI-relevant ist oder nicht. Nachdem in meinen Steuerklassen allerdings "Umsatzsteuerpflichtige Güter 10%" und "Umsatzsteuerpflichtige Güter 20%" zu finden ist, nehme ich an, dass "Österreich" beim Setup berücksichtigt würde.
UX ist hier jedenfalls verbesserungswürdig.
