### ISSUE TITLE
Vorschlag: Telefonnummer verlinken

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-germansetup#82]
Fände es cool, wenn die Telefonnumer, wie auch die E-Mail Adresse automatisch verlinkt würde.

Denke das ist inzwischen Standard und z.B. kann man so nicht die Felder aus dem Backend für das Impressum nehmen, da es nicht verlinkt ist.

Meinungen?

**Comment by riconeitzel** [comment]
Also ich zumindest hab's nicht verstanden … was genau meinst du mit "verlinken" ?! LG rico

**Comment by avstudnitz** [comment]
Duplicate of #90
