### ISSUE TITLE
Zahlungsart Rechnung

### ISSUE THREAD

**Issue by chriswalg** [firegento/firegento-germansetup#89]
Die Zahlungsart Rechnung fehlt leider noch. Man kann zwar die Zahlart Scheck dazu missbrauchen, aber dabei, kann man den Ordner-Status nicht verändern.

**Comment by mklooss** [comment]
Das ist denke ich nicht Bestandteil von GS, da dieses nicht für jeden Kunden gilt.

Meine Erfahrung ist, dass hier die Kunden eher auf Dienstleister setzen, die eine Boniprüfung machen

**Comment by therouv** [comment]
Wird kein Bestandteil von GermanSetup werden. Man könnte aber überlegen ein eigenes FireGento-Invoice-Modul zu entwickeln.

Issue wird geschlossen.

**Comment by JHelmetDago** [comment]
Muss da chriswalg unterstützen. Zahlungsart Rechnung ist meiner Erfahrung nach die meist genutzte im Versand- und Onlinehandel. Und Boniprüfung ist v.a. bei  Bestandskunden nicht notwendig. Würde das Modul gut abrunden.

**Comment by drlrdsen** [comment]
Wie von Rouven richtig angedeutet, kann sowas gern Bestandteil eines separaten Moduls sein, aber mit einem Deutschen Setup hat die Funktionalität nichts am Hut. Ein Ziel von German Setup war die Reduzierung auf das Wesentliche und nicht die Integration jeder möglichen Funktionalität.

**Comment by grossmann** [comment]
Ab Version 1.7.x bietet Magento doch die Zahlungsart "Purchase order" an. Das entspricht doch der Zahlung auf Rechnung. Einziges Problem dabei ist, dass diese häufig nicht für alle Kunden (oder erst nach Prüfung) freigeschalten werden soll. Da wäre eine Erweiterung sinnvoll, die eine Nutzung auf Kundenbasis (auf Gruppenbasis geht nicht das Gruppen für die Steuerzuordnung benötigt werden) einschränkt. Hat jedoch mit GermanSetup wirklich nix zu tun.
