### ISSUE TITLE
Newsletter Unsubscribe as Guest

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-germansetup#91]
Momentan ist es nur Kunden möglich sich wieder vom Newsletter abzumelden, aber nicht Gäste über die Seite.

Hinzukommt bei "Double Opt-In" keine Bestätigung (per E-Mail) dass man wirklich den Newsletter angemeldet hat.

Habe das ganze schon mal als Modul gebaut.
https://github.com/mklooss/Magento-Unsubscribe-Newsletter

Es wird unter dem Standard Newsletter Block noch ein Block geladen, welcher ähnlich aussieht, nur zum Abmelden des NLs ist.

**Comment by mklooss** [comment]
habe die Extension im Github Namen verändert: https://github.com/mklooss/Loewenstark_Newsletter
und heute bei Connect hochgeladen:
(ebenso composer und modman files hinzugefügt)
Connect Link: http://www.magentocommerce.com/magento-connect/catalog/product/view/id/15534/

Da es doch zu fett ist für eine GermanSetup Implementation

**Comment by avstudnitz** [comment]
Sehr gut, ist ja auch nicht speziell Deutsch. Kannst du das in der Liste der empfohlenen Erweiterungen aufnehmen und einen Pull Request dazu erstellen? Danke.

**Comment by mklooss** [comment]
Alles klar.

Werde ich dann machen, habe es aber erstmal doch von Magento Connect zurückgezogen, da ich doch noch einige Elemente verändern werde. und sobald es auf Magento Connect dann ist, kann ich den PullRequest hier machen.

**Comment by therouv** [comment]
Danke dir. Solange du das Modul noch veränderst, schließe ich einmal hier das Issue.
