### ISSUE TITLE
Autoinstaller

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-germansetup#95]
I want to autoinstall germansetup.

This means, I deploy it via modman or composer and set a config-value in another "Install" extension with my default values. I'm talking about a clean installation, so I don't need  to be sure not overwritting anything.

If this config key is set german setup is installed automatically.

I see three ways to implement this:
1. using a install script - will be hidden in the install scripts (not nice)
2. using a observer which listens on any event which is thrown every time, checks wether this key exists and installs german setup
3. another extension (which uninstalls itself after installing?)

Any recommendations?

The next step would be a configurationfor the setup in the configuration :)

**Comment by avstudnitz** [comment]
I like the idea and will need something like that in an upcoming project. That's one reason why I support this Autoinstaller (I'd call it remote installer) feature. It will be handy for shops which will have an automatic deployment and where no changes are made to the database directly, but all changes are made through setup scripts.

I'd like to have a possibility to call it via PHP, i.e. something like:

``` php
Mage::getModel('germansetup/launcher')->setup(array(
    'country' => 'de',
...
));
```

You'd need to set the configuration only if it differs from the default values.
You can call it from setup scripts, other modules or whatever. It would need moving some logic out of the controller into a model.

**Comment by avstudnitz** [comment]
Just started development on that.

**Comment by avstudnitz** [comment]
Implemented in development branch.
Usage:

``` php
Mage::getModel('germansetup/setup')->setup();
```

This starts the setup as if an admin user sent the pre-filled adminhtml form. 
If you want to adjust some settings, you can add parameters:

``` php
Mage::getModel('germansetup/setup')->setup(array(
    'country' => 'ch',
    'email_locale' => 'de_CH', // requires de_CH language pack installed
    'overwrite_emails' => true,
    'cms' => false, // disable cms setup
    'product_tax_class_target' => array(4 => 1), // set tax class of products with old tax class 2 to new tax class 1
));
```

Full list of default parameters:

```
'country'                   => 'de',
'systemconfig'              => true,
'cms'                       => true,
'agreements'                => true,
'email'                     => true,
'email_locale'              => 'de_DE',
'overwrite_emails'          => false,
'tax'                       => true,
'product_tax_class_target'  => $productTaxClassTargets, // depends on existing tax classes
```

As I had to change the adminhtml controller and the setup classes too, please review and test. (@Schrank ? @therouv ?) I'd like to merge it to master and release it on MagentoConnect soon (as v1.2.0).

**Comment by therouv** [comment]
Vergessen zu antworten:
Hatte ich getestet, von dem her :+1:
