### ISSUE TITLE
Keine Mailadressen im Klartext

### ISSUE THREAD

**Issue by grossmann** [firegento/firegento-germansetup#99]
Mailadressen werden im Moment als Klartext (auch mit deaktiviertem JS) z.B. im Impressum dargestellt. Das ermöglicht Spambots das sammeln der Mails. Schön wäre eine Möglichkeit, diese durch JS erst zu gültigen Maillinks zu verarbeiten, da die Spambots diesen nicht auswerten können. Bsp.: http://www.spamspan.de/

**Comment by mklooss** [comment]
naja sowas kann man in der heutigen Zeit eh vergessen, da sowas mittels einfachen Scripten zu lesen ist.
und viele Spamparser können auch schon JavaScript...

Die Auf der genannten Seite lassen sich bspw. alles Problemlos mit Regulären Ausdrücken wieder in eine E-Mail zurück verwandeln...

Zu dem bringt es nur bedingt, da viele mail@, info@, etc. verwenden, wo eh die Spammer hinsenden.

Ich würde da eher Energie in Spamassassin und Amavisd-new oder ähnliche Systeme setzen.

**Comment by riconeitzel** [comment]
sehe ich auch so wie mklooss – die robots sind mittlerweile ziemlich schlau, können OCR CSS und JS Tricks locker aushebeln. Ggf. wäre das, wenn unbedingt gewünscht, ein weiteres Modul, was alle Ausgaben des Blockrenderers nochmal durch nen Parser pfeift und die Adressen maskiert. Aber mit einem GermanSetup zur rechtlichen Vorbereitung  eines Shops auf die deutschen Gesetzes-Stromschnellen hat das m.E. nichts zu tun. Das würde die Extension verwässern und den Pflegeaufwand erhöhen.

**Comment by avstudnitz** [comment]
Jepp, sehe ich genauso.

**Comment by grossmann** [comment]
OK
